# Dashboards need to be specified here
# A prow annotation will be invalid if it references a dashboard that doesn't exist
dashboards:
- name: istio_api
- name: istio_api_postsubmit
- name: istio_bots
- name: istio_bots_postsubmit
- name: istio_client-go
- name: istio_client-go_postsubmit
- name: istio_common-files
- name: istio_common-files_postsubmit
- name: istio_community
- name: istio_community_postsubmit
- name: istio_enhancements
- name: istio_envoy
- name: istio_infrastructure
- name: istio_istio
- name: istio_istio.io
- name: istio_istio.io_postsubmit
- name: istio_istio.io_periodic
- name: istio_istio_postsubmit
- name: istio_istio_periodic
- name: istio_proxy
- name: istio_proxy_periodic
- name: istio_proxy_postsubmit
- name: istio_experimental-ambient_istio
- name: istio_experimental-ambient_istio_postsubmit
- name: istio_ztunnel
- name: istio_ztunnel_postsubmit
- name: istio_release-builder_periodic
- name: istio_release-1.18_istio
- name: istio_release-1.18_api
- name: istio_release-1.18_client-go
- name: istio_release-1.18_common-files
- name: istio_release-1.18_istio.io
- name: istio_release-1.18_pkg
- name: istio_release-1.18_proxy
- name: istio_release-1.18_tools
- name: istio_release-1.18_release-builder
- name: istio_release-1.18_istio_postsubmit
- name: istio_release-1.18_client-go_postsubmit
- name: istio_release-1.18_common-files_postsubmit
- name: istio_release-1.18_istio.io_postsubmit
- name: istio_release-1.18_pkg_postsubmit
- name: istio_release-1.18_proxy_periodic
- name: istio_release-1.18_proxy_postsubmit
- name: istio_release-1.18_api_postsubmit
- name: istio_release-1.18_tools_postsubmit
- name: istio_release-1.18_release-builder_postsubmit
- name: istio_release-1.18_release-builder_periodic
- name: istio_release-1.18_istio_periodic
- name: istio_release-1.18_enhancements
- name: istio_release-1.18_ztunnel
- name: istio_release-1.18_ztunnel_postsubmit
- name: istio_release-1.17_istio
- name: istio_release-1.17_api
- name: istio_release-1.17_client-go
- name: istio_release-1.17_common-files
- name: istio_release-1.17_istio.io
- name: istio_release-1.17_pkg
- name: istio_release-1.17_proxy
- name: istio_release-1.17_tools
- name: istio_release-1.17_release-builder
- name: istio_release-1.17_istio_postsubmit
- name: istio_release-1.17_client-go_postsubmit
- name: istio_release-1.17_common-files_postsubmit
- name: istio_release-1.17_istio.io_postsubmit
- name: istio_release-1.17_pkg_postsubmit
- name: istio_release-1.17_proxy_periodic
- name: istio_release-1.17_proxy_postsubmit
- name: istio_release-1.17_api_postsubmit
- name: istio_release-1.17_tools_postsubmit
- name: istio_release-1.17_release-builder_postsubmit
- name: istio_release-1.17_release-builder_periodic
- name: istio_release-1.17_istio_periodic
- name: istio_release-1.17_enhancements
- name: istio_release-1.16_istio
- name: istio_release-1.16_api
- name: istio_release-1.16_client-go
- name: istio_release-1.16_common-files
- name: istio_release-1.16_istio.io
- name: istio_release-1.16_pkg
- name: istio_release-1.16_proxy
- name: istio_release-1.16_tools
- name: istio_release-1.16_release-builder
- name: istio_release-1.16_istio_postsubmit
- name: istio_release-1.16_client-go_postsubmit
- name: istio_release-1.16_common-files_postsubmit
- name: istio_release-1.16_istio.io_postsubmit
- name: istio_release-1.16_pkg_postsubmit
- name: istio_release-1.16_proxy_periodic
- name: istio_release-1.16_proxy_postsubmit
- name: istio_release-1.16_api_postsubmit
- name: istio_release-1.16_tools_postsubmit
- name: istio_release-1.16_release-builder_postsubmit
- name: istio_release-1.16_release-builder_periodic
- name: istio_release-1.16_istio_periodic
- name: istio_release-1.16_enhancements
- name: istio_release-builder_postsubmit
- name: istio_release-builder
- name: istio_test-infra
- name: istio_test-infra_postsubmit
- name: istio_test-infra_periodic
- name: istio_tools
- name: istio_tools_postsubmit
# Group all dashboards
dashboard_groups:
- name: istio_release-1.18
  dashboard_names:
  - istio_release-1.18_api
  - istio_release-1.18_api_postsubmit
  - istio_release-1.18_client-go
  - istio_release-1.18_client-go_postsubmit
  - istio_release-1.18_common-files
  - istio_release-1.18_common-files_postsubmit
  - istio_release-1.18_enhancements
  - istio_release-1.18_istio
  - istio_release-1.18_istio.io
  - istio_release-1.18_istio.io_postsubmit
  - istio_release-1.18_istio_periodic
  - istio_release-1.18_istio_postsubmit
  - istio_release-1.18_pkg
  - istio_release-1.18_pkg_postsubmit
  - istio_release-1.18_proxy
  - istio_release-1.18_proxy_periodic
  - istio_release-1.18_proxy_postsubmit
  - istio_release-1.18_release-builder
  - istio_release-1.18_release-builder_periodic
  - istio_release-1.18_release-builder_postsubmit
  - istio_release-1.18_tools
  - istio_release-1.18_tools_postsubmit
  - istio_release-1.18_ztunnel_postsubmit
  - istio_release-1.18_ztunnel
- name: istio_release-1.17
  dashboard_names:
  - istio_release-1.17_api
  - istio_release-1.17_api_postsubmit
  - istio_release-1.17_client-go
  - istio_release-1.17_client-go_postsubmit
  - istio_release-1.17_common-files
  - istio_release-1.17_common-files_postsubmit
  - istio_release-1.17_enhancements
  - istio_release-1.17_istio
  - istio_release-1.17_istio.io
  - istio_release-1.17_istio.io_postsubmit
  - istio_release-1.17_istio_periodic
  - istio_release-1.17_istio_postsubmit
  - istio_release-1.17_pkg
  - istio_release-1.17_pkg_postsubmit
  - istio_release-1.17_proxy
  - istio_release-1.17_proxy_periodic
  - istio_release-1.17_proxy_postsubmit
  - istio_release-1.17_release-builder
  - istio_release-1.17_release-builder_periodic
  - istio_release-1.17_release-builder_postsubmit
  - istio_release-1.17_tools
  - istio_release-1.17_tools_postsubmit
- name: istio_release-1.16
  dashboard_names:
  - istio_release-1.16_api
  - istio_release-1.16_api_postsubmit
  - istio_release-1.16_client-go
  - istio_release-1.16_client-go_postsubmit
  - istio_release-1.16_common-files
  - istio_release-1.16_common-files_postsubmit
  - istio_release-1.16_enhancements
  - istio_release-1.16_istio
  - istio_release-1.16_istio.io
  - istio_release-1.16_istio.io_postsubmit
  - istio_release-1.16_istio_periodic
  - istio_release-1.16_istio_postsubmit
  - istio_release-1.16_pkg
  - istio_release-1.16_pkg_postsubmit
  - istio_release-1.16_proxy
  - istio_release-1.16_proxy_periodic
  - istio_release-1.16_proxy_postsubmit
  - istio_release-1.16_release-builder
  - istio_release-1.16_release-builder_periodic
  - istio_release-1.16_release-builder_postsubmit
  - istio_release-1.16_tools
  - istio_release-1.16_tools_postsubmit
- name: istio
  dashboard_names:
  - istio_istio.io_periodic
  - istio_test-infra_periodic
  - istio_istio_postsubmit
  - istio_istio_periodic
  - istio_api_postsubmit
  - istio_bots_postsubmit
  - istio_client-go_postsubmit
  - istio_experimental-ambient_istio_postsubmit
  - istio_ztunnel_postsubmit
  - istio_common-files_postsubmit
  - istio_community_postsubmit
  - istio_istio.io_postsubmit
  - istio_proxy_postsubmit
  - istio_test-infra_postsubmit
  - istio_tools_postsubmit
  - istio_istio
  - istio_api
  - istio_bots
  - istio_client-go
  - istio_experimental-ambient_istio
  - istio_ztunnel
  - istio_common-files
  - istio_community
  - istio_envoy
  - istio_infrastructure
  - istio_istio.io
  - istio_proxy
  - istio_proxy_periodic
  - istio_test-infra
  - istio_tools
  - istio_enhancements
  - istio_release-builder
  - istio_release-builder_periodic
  - istio_release-builder_postsubmit
