# Dashboards need to be specified here
# A prow annotation will be invalid if it references a dashboard that doesn't exist
dashboards:
- name: istio_api
- name: istio_api_postsubmit
- name: istio_bots
- name: istio_bots_postsubmit
- name: istio_client-go
- name: istio_client-go_postsubmit
- name: istio_common-files
- name: istio_common-files_postsubmit
- name: istio_community
- name: istio_community_postsubmit
- name: istio_enhancements
- name: istio_infrastructure
- name: istio_istio
- name: istio_istio.io
- name: istio_istio.io_postsubmit
- name: istio_istio.io_periodic
- name: istio_istio_postsubmit
- name: istio_istio_periodic
- name: istio_proxy
- name: istio_proxy_periodic
- name: istio_proxy_postsubmit
- name: istio_ztunnel
- name: istio_ztunnel_postsubmit
- name: istio_release-builder_periodic
- name: istio_release-1.28_istio
- name: istio_release-1.28_api
- name: istio_release-1.28_client-go
- name: istio_release-1.28_common-files
- name: istio_release-1.28_istio.io
- name: istio_release-1.28_proxy
- name: istio_release-1.28_tools
- name: istio_release-1.28_release-builder
- name: istio_release-1.28_istio_postsubmit
- name: istio_release-1.28_client-go_postsubmit
- name: istio_release-1.28_common-files_postsubmit
- name: istio_release-1.28_istio.io_postsubmit
- name: istio_release-1.28_proxy_periodic
- name: istio_release-1.28_proxy_postsubmit
- name: istio_release-1.28_api_postsubmit
- name: istio_release-1.28_tools_postsubmit
- name: istio_release-1.28_release-builder_postsubmit
- name: istio_release-1.28_release-builder_periodic
- name: istio_release-1.28_istio_periodic
- name: istio_release-1.28_enhancements
- name: istio_release-1.28_ztunnel
- name: istio_release-1.28_ztunnel_postsubmit
- name: istio_release-1.27_istio
- name: istio_release-1.27_api
- name: istio_release-1.27_client-go
- name: istio_release-1.27_common-files
- name: istio_release-1.27_istio.io
- name: istio_release-1.27_proxy
- name: istio_release-1.27_tools
- name: istio_release-1.27_release-builder
- name: istio_release-1.27_istio_postsubmit
- name: istio_release-1.27_client-go_postsubmit
- name: istio_release-1.27_common-files_postsubmit
- name: istio_release-1.27_istio.io_postsubmit
- name: istio_release-1.27_proxy_periodic
- name: istio_release-1.27_proxy_postsubmit
- name: istio_release-1.27_api_postsubmit
- name: istio_release-1.27_tools_postsubmit
- name: istio_release-1.27_release-builder_postsubmit
- name: istio_release-1.27_release-builder_periodic
- name: istio_release-1.27_istio_periodic
- name: istio_release-1.27_enhancements
- name: istio_release-1.27_ztunnel
- name: istio_release-1.27_ztunnel_postsubmit
- name: istio_release-1.26_istio
- name: istio_release-1.26_api
- name: istio_release-1.26_client-go
- name: istio_release-1.26_common-files
- name: istio_release-1.26_istio.io
- name: istio_release-1.26_proxy
- name: istio_release-1.26_tools
- name: istio_release-1.26_release-builder
- name: istio_release-1.26_istio_postsubmit
- name: istio_release-1.26_client-go_postsubmit
- name: istio_release-1.26_common-files_postsubmit
- name: istio_release-1.26_istio.io_postsubmit
- name: istio_release-1.26_proxy_periodic
- name: istio_release-1.26_proxy_postsubmit
- name: istio_release-1.26_api_postsubmit
- name: istio_release-1.26_tools_postsubmit
- name: istio_release-1.26_release-builder_postsubmit
- name: istio_release-1.26_release-builder_periodic
- name: istio_release-1.26_istio_periodic
- name: istio_release-1.26_enhancements
- name: istio_release-1.26_ztunnel
- name: istio_release-1.26_ztunnel_postsubmit
- name: istio_release-1.25_istio
- name: istio_release-1.25_api
- name: istio_release-1.25_client-go
- name: istio_release-1.25_common-files
- name: istio_release-1.25_istio.io
- name: istio_release-1.25_proxy
- name: istio_release-1.25_tools
- name: istio_release-1.25_release-builder
- name: istio_release-1.25_istio_postsubmit
- name: istio_release-1.25_client-go_postsubmit
- name: istio_release-1.25_common-files_postsubmit
- name: istio_release-1.25_istio.io_postsubmit
- name: istio_release-1.25_proxy_periodic
- name: istio_release-1.25_proxy_postsubmit
- name: istio_release-1.25_api_postsubmit
- name: istio_release-1.25_tools_postsubmit
- name: istio_release-1.25_release-builder_postsubmit
- name: istio_release-1.25_release-builder_periodic
- name: istio_release-1.25_istio_periodic
- name: istio_release-1.25_enhancements
- name: istio_release-1.25_ztunnel
- name: istio_release-1.25_ztunnel_postsubmit
- name: istio_release-builder_postsubmit
- name: istio_release-builder
- name: istio_test-infra
- name: istio_test-infra_postsubmit
- name: istio_test-infra_periodic
- name: istio_tools
- name: istio_tools_postsubmit
- name: istio-ecosystem_main_sail-operator
- name: istio-ecosystem_release-0.1_sail-operator
- name: istio-ecosystem_release-0.2_sail-operator
- name: istio-ecosystem_release-1.0_sail-operator
- name: istio-ecosystem_release-1.25_sail-operator
- name: istio-ecosystem_release-1.26_sail-operator
- name: istio-ecosystem_release-1.27_sail-operator
# Group all dashboards
dashboard_groups:
- name: istio_release-1.28
  dashboard_names:
  - istio_release-1.28_api
  - istio_release-1.28_api_postsubmit
  - istio_release-1.28_client-go
  - istio_release-1.28_client-go_postsubmit
  - istio_release-1.28_common-files
  - istio_release-1.28_common-files_postsubmit
  - istio_release-1.28_enhancements
  - istio_release-1.28_istio
  - istio_release-1.28_istio.io
  - istio_release-1.28_istio.io_postsubmit
  - istio_release-1.28_istio_periodic
  - istio_release-1.28_istio_postsubmit
  - istio_release-1.28_proxy
  - istio_release-1.28_proxy_periodic
  - istio_release-1.28_proxy_postsubmit
  - istio_release-1.28_release-builder
  - istio_release-1.28_release-builder_periodic
  - istio_release-1.28_release-builder_postsubmit
  - istio_release-1.28_tools
  - istio_release-1.28_tools_postsubmit
  - istio_release-1.28_ztunnel_postsubmit
  - istio_release-1.28_ztunnel
- name: istio_release-1.27
  dashboard_names:
  - istio_release-1.27_api
  - istio_release-1.27_api_postsubmit
  - istio_release-1.27_client-go
  - istio_release-1.27_client-go_postsubmit
  - istio_release-1.27_common-files
  - istio_release-1.27_common-files_postsubmit
  - istio_release-1.27_enhancements
  - istio_release-1.27_istio
  - istio_release-1.27_istio.io
  - istio_release-1.27_istio.io_postsubmit
  - istio_release-1.27_istio_periodic
  - istio_release-1.27_istio_postsubmit
  - istio_release-1.27_proxy
  - istio_release-1.27_proxy_periodic
  - istio_release-1.27_proxy_postsubmit
  - istio_release-1.27_release-builder
  - istio_release-1.27_release-builder_periodic
  - istio_release-1.27_release-builder_postsubmit
  - istio_release-1.27_tools
  - istio_release-1.27_tools_postsubmit
  - istio_release-1.27_ztunnel_postsubmit
  - istio_release-1.27_ztunnel
- name: istio_release-1.26
  dashboard_names:
  - istio_release-1.26_api
  - istio_release-1.26_api_postsubmit
  - istio_release-1.26_client-go
  - istio_release-1.26_client-go_postsubmit
  - istio_release-1.26_common-files
  - istio_release-1.26_common-files_postsubmit
  - istio_release-1.26_enhancements
  - istio_release-1.26_istio
  - istio_release-1.26_istio.io
  - istio_release-1.26_istio.io_postsubmit
  - istio_release-1.26_istio_periodic
  - istio_release-1.26_istio_postsubmit
  - istio_release-1.26_proxy
  - istio_release-1.26_proxy_periodic
  - istio_release-1.26_proxy_postsubmit
  - istio_release-1.26_release-builder
  - istio_release-1.26_release-builder_periodic
  - istio_release-1.26_release-builder_postsubmit
  - istio_release-1.26_tools
  - istio_release-1.26_tools_postsubmit
  - istio_release-1.26_ztunnel_postsubmit
  - istio_release-1.26_ztunnel
- name: istio_release-1.25
  dashboard_names:
  - istio_release-1.25_api
  - istio_release-1.25_api_postsubmit
  - istio_release-1.25_client-go
  - istio_release-1.25_client-go_postsubmit
  - istio_release-1.25_common-files
  - istio_release-1.25_common-files_postsubmit
  - istio_release-1.25_enhancements
  - istio_release-1.25_istio
  - istio_release-1.25_istio.io
  - istio_release-1.25_istio.io_postsubmit
  - istio_release-1.25_istio_periodic
  - istio_release-1.25_istio_postsubmit
  - istio_release-1.25_proxy
  - istio_release-1.25_proxy_periodic
  - istio_release-1.25_proxy_postsubmit
  - istio_release-1.25_release-builder
  - istio_release-1.25_release-builder_periodic
  - istio_release-1.25_release-builder_postsubmit
  - istio_release-1.25_tools
  - istio_release-1.25_tools_postsubmit
  - istio_release-1.25_ztunnel_postsubmit
  - istio_release-1.25_ztunnel
- name: istio
  dashboard_names:
  - istio_istio.io_periodic
  - istio_test-infra_periodic
  - istio_istio_postsubmit
  - istio_istio_periodic
  - istio_api_postsubmit
  - istio_bots_postsubmit
  - istio_client-go_postsubmit
  - istio_ztunnel_postsubmit
  - istio_common-files_postsubmit
  - istio_community_postsubmit
  - istio_istio.io_postsubmit
  - istio_proxy_postsubmit
  - istio_test-infra_postsubmit
  - istio_tools_postsubmit
  - istio_istio
  - istio_api
  - istio_bots
  - istio_client-go
  - istio_ztunnel
  - istio_common-files
  - istio_community
  - istio_infrastructure
  - istio_istio.io
  - istio_proxy
  - istio_proxy_periodic
  - istio_test-infra
  - istio_tools
  - istio_enhancements
  - istio_release-builder
  - istio_release-builder_periodic
  - istio_release-builder_postsubmit
- name: istio-ecosystem
  dashboard_names:
  - istio-ecosystem_main_sail-operator
  - istio-ecosystem_release-0.1_sail-operator
  - istio-ecosystem_release-0.2_sail-operator
  - istio-ecosystem_release-1.0_sail-operator
  - istio-ecosystem_release-1.25_sail-operator
  - istio-ecosystem_release-1.26_sail-operator
  - istio-ecosystem_release-1.27_sail-operator
  - istio-ecosystem_release-1.28_sail-operator
