# Dashboards need to be specified here
# A prow annotation will be invalid if it references a dashboard that doesn't exist
dashboards:
- name: istio_api
- name: istio_api_postsubmit
- name: istio_bots
- name: istio_bots_postsubmit
- name: istio_client-go
- name: istio_client-go_postsubmit
- name: istio_common-files
- name: istio_common-files_postsubmit
- name: istio_community
- name: istio_community_postsubmit
- name: istio_enhancements
- name: istio_infrastructure
- name: istio_istio
- name: istio_istio.io
- name: istio_istio.io_postsubmit
- name: istio_istio.io_periodic
- name: istio_istio_postsubmit
- name: istio_istio_periodic
- name: istio_proxy
- name: istio_proxy_periodic
- name: istio_proxy_postsubmit
- name: istio_ztunnel
- name: istio_ztunnel_postsubmit
- name: istio_release-builder_periodic
- name: istio_release-1.24_istio
- name: istio_release-1.24_api
- name: istio_release-1.24_client-go
- name: istio_release-1.24_common-files
- name: istio_release-1.24_istio.io
- name: istio_release-1.24_proxy
- name: istio_release-1.24_tools
- name: istio_release-1.24_release-builder
- name: istio_release-1.24_istio_postsubmit
- name: istio_release-1.24_client-go_postsubmit
- name: istio_release-1.24_common-files_postsubmit
- name: istio_release-1.24_istio.io_postsubmit
- name: istio_release-1.24_proxy_periodic
- name: istio_release-1.24_proxy_postsubmit
- name: istio_release-1.24_api_postsubmit
- name: istio_release-1.24_tools_postsubmit
- name: istio_release-1.24_release-builder_postsubmit
- name: istio_release-1.24_release-builder_periodic
- name: istio_release-1.24_istio_periodic
- name: istio_release-1.24_enhancements
- name: istio_release-1.24_ztunnel
- name: istio_release-1.24_ztunnel_postsubmit
- name: istio_release-1.23_istio
- name: istio_release-1.23_api
- name: istio_release-1.23_client-go
- name: istio_release-1.23_common-files
- name: istio_release-1.23_istio.io
- name: istio_release-1.23_proxy
- name: istio_release-1.23_tools
- name: istio_release-1.23_release-builder
- name: istio_release-1.23_istio_postsubmit
- name: istio_release-1.23_client-go_postsubmit
- name: istio_release-1.23_common-files_postsubmit
- name: istio_release-1.23_istio.io_postsubmit
- name: istio_release-1.23_proxy_periodic
- name: istio_release-1.23_proxy_postsubmit
- name: istio_release-1.23_api_postsubmit
- name: istio_release-1.23_tools_postsubmit
- name: istio_release-1.23_release-builder_postsubmit
- name: istio_release-1.23_release-builder_periodic
- name: istio_release-1.23_istio_periodic
- name: istio_release-1.23_enhancements
- name: istio_release-1.23_ztunnel
- name: istio_release-1.23_ztunnel_postsubmit
- name: istio_release-1.22_istio
- name: istio_release-1.22_api
- name: istio_release-1.22_client-go
- name: istio_release-1.22_common-files
- name: istio_release-1.22_istio.io
- name: istio_release-1.22_proxy
- name: istio_release-1.22_tools
- name: istio_release-1.22_release-builder
- name: istio_release-1.22_istio_postsubmit
- name: istio_release-1.22_client-go_postsubmit
- name: istio_release-1.22_common-files_postsubmit
- name: istio_release-1.22_istio.io_postsubmit
- name: istio_release-1.22_proxy_periodic
- name: istio_release-1.22_proxy_postsubmit
- name: istio_release-1.22_api_postsubmit
- name: istio_release-1.22_tools_postsubmit
- name: istio_release-1.22_release-builder_postsubmit
- name: istio_release-1.22_release-builder_periodic
- name: istio_release-1.22_istio_periodic
- name: istio_release-1.22_enhancements
- name: istio_release-1.22_ztunnel
- name: istio_release-1.22_ztunnel_postsubmit
- name: istio_release-builder_postsubmit
- name: istio_release-builder
- name: istio_test-infra
- name: istio_test-infra_postsubmit
- name: istio_test-infra_periodic
- name: istio_tools
- name: istio_tools_postsubmit
- name: istio-ecosystem_main_sail-operator
- name: istio-ecosystem_release-0.1_sail-operator
# Group all dashboards
dashboard_groups:
- name: istio_release-1.24
  dashboard_names:
  - istio_release-1.24_api
  - istio_release-1.24_api_postsubmit
  - istio_release-1.24_client-go
  - istio_release-1.24_client-go_postsubmit
  - istio_release-1.24_common-files
  - istio_release-1.24_common-files_postsubmit
  - istio_release-1.24_enhancements
  - istio_release-1.24_istio
  - istio_release-1.24_istio.io
  - istio_release-1.24_istio.io_postsubmit
  - istio_release-1.24_istio_periodic
  - istio_release-1.24_istio_postsubmit
  - istio_release-1.24_proxy
  - istio_release-1.24_proxy_periodic
  - istio_release-1.24_proxy_postsubmit
  - istio_release-1.24_release-builder
  - istio_release-1.24_release-builder_periodic
  - istio_release-1.24_release-builder_postsubmit
  - istio_release-1.24_tools
  - istio_release-1.24_tools_postsubmit
  - istio_release-1.24_ztunnel_postsubmit
  - istio_release-1.24_ztunnel
- name: istio_release-1.23
  dashboard_names:
  - istio_release-1.23_api
  - istio_release-1.23_api_postsubmit
  - istio_release-1.23_client-go
  - istio_release-1.23_client-go_postsubmit
  - istio_release-1.23_common-files
  - istio_release-1.23_common-files_postsubmit
  - istio_release-1.23_enhancements
  - istio_release-1.23_istio
  - istio_release-1.23_istio.io
  - istio_release-1.23_istio.io_postsubmit
  - istio_release-1.23_istio_periodic
  - istio_release-1.23_istio_postsubmit
  - istio_release-1.23_proxy
  - istio_release-1.23_proxy_periodic
  - istio_release-1.23_proxy_postsubmit
  - istio_release-1.23_release-builder
  - istio_release-1.23_release-builder_periodic
  - istio_release-1.23_release-builder_postsubmit
  - istio_release-1.23_tools
  - istio_release-1.23_tools_postsubmit
  - istio_release-1.23_ztunnel_postsubmit
  - istio_release-1.23_ztunnel
- name: istio_release-1.22
  dashboard_names:
  - istio_release-1.22_api
  - istio_release-1.22_api_postsubmit
  - istio_release-1.22_client-go
  - istio_release-1.22_client-go_postsubmit
  - istio_release-1.22_common-files
  - istio_release-1.22_common-files_postsubmit
  - istio_release-1.22_enhancements
  - istio_release-1.22_istio
  - istio_release-1.22_istio.io
  - istio_release-1.22_istio.io_postsubmit
  - istio_release-1.22_istio_periodic
  - istio_release-1.22_istio_postsubmit
  - istio_release-1.22_proxy
  - istio_release-1.22_proxy_periodic
  - istio_release-1.22_proxy_postsubmit
  - istio_release-1.22_release-builder
  - istio_release-1.22_release-builder_periodic
  - istio_release-1.22_release-builder_postsubmit
  - istio_release-1.22_tools
  - istio_release-1.22_tools_postsubmit
  - istio_release-1.22_ztunnel_postsubmit
  - istio_release-1.22_ztunnel
- name: istio
  dashboard_names:
  - istio_istio.io_periodic
  - istio_test-infra_periodic
  - istio_istio_postsubmit
  - istio_istio_periodic
  - istio_api_postsubmit
  - istio_bots_postsubmit
  - istio_client-go_postsubmit
  - istio_ztunnel_postsubmit
  - istio_common-files_postsubmit
  - istio_community_postsubmit
  - istio_istio.io_postsubmit
  - istio_proxy_postsubmit
  - istio_test-infra_postsubmit
  - istio_tools_postsubmit
  - istio_istio
  - istio_api
  - istio_bots
  - istio_client-go
  - istio_ztunnel
  - istio_common-files
  - istio_community
  - istio_infrastructure
  - istio_istio.io
  - istio_proxy
  - istio_proxy_periodic
  - istio_test-infra
  - istio_tools
  - istio_enhancements
  - istio_release-builder
  - istio_release-builder_periodic
  - istio_release-builder_postsubmit
- name: istio-ecosystem
  dashboard_names:
  - istio-ecosystem_main_sail-operator
  - istio-ecosystem_release-0.1_sail-operator
