# Dashboards need to be specified here
# A prow annotation will be invalid if it references a dashboard that doesn't exist
dashboards:
- name: istio_api
- name: istio_api_postsubmit
- name: istio_bots
- name: istio_bots_postsubmit
- name: istio_client-go
- name: istio_client-go_postsubmit
- name: istio_cri
- name: istio_cri_postsubmit
- name: istio_common-files
- name: istio_common-files_postsubmit
- name: istio_community
- name: istio_community_postsubmit
- name: istio_enhancements
- name: istio_envoy
- name: istio_infrastructure
- name: istio_istio
- name: istio_istio.io
- name: istio_istio.io_postsubmit
- name: istio_istio.io_periodic
- name: istio_istio_postsubmit
- name: istio_istio_periodic
- name: istio_pkg
- name: istio_pkg_postsubmit
- name: istio_proxy
- name: istio_proxy_periodic
- name: istio_proxy_postsubmit
- name: istio_release-builder_periodic
- name: istio_release-1.15_istio
- name: istio_release-1.15_api
- name: istio_release-1.15_client-go
- name: istio_release-1.15_common-files
- name: istio_release-1.15_istio.io
- name: istio_release-1.15_pkg
- name: istio_release-1.15_proxy
- name: istio_release-1.15_tools
- name: istio_release-1.15_release-builder
- name: istio_release-1.15_istio_postsubmit
- name: istio_release-1.15_client-go_postsubmit
- name: istio_release-1.15_common-files_postsubmit
- name: istio_release-1.15_istio.io_postsubmit
- name: istio_release-1.15_pkg_postsubmit
- name: istio_release-1.15_proxy_periodic
- name: istio_release-1.15_proxy_postsubmit
- name: istio_release-1.15_api_postsubmit
- name: istio_release-1.15_tools_postsubmit
- name: istio_release-1.15_release-builder_postsubmit
- name: istio_release-1.15_release-builder_periodic
- name: istio_release-1.15_istio_periodic
- name: istio_release-1.15_enhancements
- name: istio_release-1.14_istio
- name: istio_release-1.14_api
- name: istio_release-1.14_client-go
- name: istio_release-1.14_common-files
- name: istio_release-1.14_envoy
- name: istio_release-1.14_istio.io
- name: istio_release-1.14_pkg
- name: istio_release-1.14_proxy
- name: istio_release-1.14_tools
- name: istio_release-1.14_release-builder
- name: istio_release-1.14_istio_postsubmit
- name: istio_release-1.14_client-go_postsubmit
- name: istio_release-1.14_common-files_postsubmit
- name: istio_release-1.14_istio.io_postsubmit
- name: istio_release-1.14_pkg_postsubmit
- name: istio_release-1.14_proxy_periodic
- name: istio_release-1.14_proxy_postsubmit
- name: istio_release-1.14_api_postsubmit
- name: istio_release-1.14_tools_postsubmit
- name: istio_release-1.14_release-builder_postsubmit
- name: istio_release-1.14_release-builder_periodic
- name: istio_release-1.14_istio_periodic
- name: istio_release-1.14_enhancements
- name: istio_release-1.13_istio
- name: istio_release-1.13_api
- name: istio_release-1.13_client-go
- name: istio_release-1.13_common-files
- name: istio_release-1.13_envoy
- name: istio_release-1.13_gogo-genproto
- name: istio_release-1.13_istio.io
- name: istio_release-1.13_pkg
- name: istio_release-1.13_proxy
- name: istio_release-1.13_tools
- name: istio_release-1.13_release-builder
- name: istio_release-1.13_istio_postsubmit
- name: istio_release-1.13_client-go_postsubmit
- name: istio_release-1.13_common-files_postsubmit
- name: istio_release-1.13_gogo-genproto_postsubmit
- name: istio_release-1.13_istio.io_postsubmit
- name: istio_release-1.13_pkg_postsubmit
- name: istio_release-1.13_proxy_periodic
- name: istio_release-1.13_proxy_postsubmit
- name: istio_release-1.13_api_postsubmit
- name: istio_release-1.13_tools_postsubmit
- name: istio_release-1.13_release-builder_postsubmit
- name: istio_release-1.13_release-builder_periodic
- name: istio_release-1.13_istio_periodic
- name: istio_release-1.13_enhancements
- name: istio_release-1.12_istio
- name: istio_release-1.12_api
- name: istio_release-1.12_client-go
- name: istio_release-1.12_common-files
- name: istio_release-1.12_envoy
- name: istio_release-1.12_gogo-genproto
- name: istio_release-1.12_istio.io
- name: istio_release-1.12_pkg
- name: istio_release-1.12_proxy
- name: istio_release-1.12_tools
- name: istio_release-1.12_release-builder
- name: istio_release-1.12_istio_postsubmit
- name: istio_release-1.12_client-go_postsubmit
- name: istio_release-1.12_common-files_postsubmit
- name: istio_release-1.12_gogo-genproto_postsubmit
- name: istio_release-1.12_istio.io_postsubmit
- name: istio_release-1.12_pkg_postsubmit
- name: istio_release-1.12_proxy_postsubmit
- name: istio_release-1.12_api_postsubmit
- name: istio_release-1.12_tools_postsubmit
- name: istio_release-1.12_release-builder_postsubmit
- name: istio_release-1.12_enhancements
- name: istio_release-1.11_istio
- name: istio_release-1.11_api
- name: istio_release-1.11_client-go
- name: istio_release-1.11_common-files
- name: istio_release-1.11_envoy
- name: istio_release-1.11_gogo-genproto
- name: istio_release-1.11_istio.io
- name: istio_release-1.11_pkg
- name: istio_release-1.11_proxy
- name: istio_release-1.11_tools
- name: istio_release-1.11_release-builder
- name: istio_release-1.11_istio_postsubmit
- name: istio_release-1.11_client-go_postsubmit
- name: istio_release-1.11_common-files_postsubmit
- name: istio_release-1.11_gogo-genproto_postsubmit
- name: istio_release-1.11_istio.io_postsubmit
- name: istio_release-1.11_pkg_postsubmit
- name: istio_release-1.11_proxy_postsubmit
- name: istio_release-1.11_api_postsubmit
- name: istio_release-1.11_tools_postsubmit
- name: istio_release-1.11_release-builder_postsubmit
- name: istio_release-1.11_enhancements
- name: istio_release-builder_postsubmit
- name: istio_release-builder
- name: istio_test-infra
- name: istio_test-infra_postsubmit
- name: istio_test-infra_periodic
- name: istio_tools
- name: istio_tools_postsubmit
# Group all dashboards
dashboard_groups:
- name: istio_release-1.15
  dashboard_names:
  - istio_release-1.15_istio_postsubmit
  - istio_release-1.15_client-go_postsubmit
  - istio_release-1.15_common-files_postsubmit
  - istio_release-1.15_istio.io_postsubmit
  - istio_release-1.15_pkg_postsubmit
  - istio_release-1.15_proxy_postsubmit
  - istio_release-1.15_api_postsubmit
  - istio_release-1.15_tools_postsubmit
  - istio_release-1.15_release-builder_postsubmit
  - istio_release-1.15_release-builder_periodic
  - istio_release-1.15_istio
  - istio_release-1.15_api
  - istio_release-1.15_client-go
  - istio_release-1.15_common-files
  - istio_release-1.15_istio.io
  - istio_release-1.15_pkg
  - istio_release-1.15_proxy
  - istio_release-1.15_tools
  - istio_release-1.15_release-builder
- name: istio_release-1.14
  dashboard_names:
  - istio_release-1.14_istio_postsubmit
  - istio_release-1.14_client-go_postsubmit
  - istio_release-1.14_common-files_postsubmit
  - istio_release-1.14_istio.io_postsubmit
  - istio_release-1.14_pkg_postsubmit
  - istio_release-1.14_proxy_postsubmit
  - istio_release-1.14_api_postsubmit
  - istio_release-1.14_tools_postsubmit
  - istio_release-1.14_release-builder_postsubmit
  - istio_release-1.14_release-builder_periodic
  - istio_release-1.14_istio
  - istio_release-1.14_api
  - istio_release-1.14_client-go
  - istio_release-1.14_common-files
  - istio_release-1.14_istio.io
  - istio_release-1.14_pkg
  - istio_release-1.14_proxy
  - istio_release-1.14_tools
  - istio_release-1.14_release-builder
- name: istio_release-1.13
  dashboard_names:
  - istio_release-1.13_istio_postsubmit
  - istio_release-1.13_client-go_postsubmit
  - istio_release-1.13_common-files_postsubmit
  - istio_release-1.13_gogo-genproto_postsubmit
  - istio_release-1.13_istio.io_postsubmit
  - istio_release-1.13_pkg_postsubmit
  - istio_release-1.13_proxy_postsubmit
  - istio_release-1.13_api_postsubmit
  - istio_release-1.13_tools_postsubmit
  - istio_release-1.13_release-builder_postsubmit
  - istio_release-1.13_release-builder_periodic
  - istio_release-1.13_istio
  - istio_release-1.13_api
  - istio_release-1.13_client-go
  - istio_release-1.13_common-files
  - istio_release-1.13_envoy
  - istio_release-1.13_gogo-genproto
  - istio_release-1.13_istio.io
  - istio_release-1.13_pkg
  - istio_release-1.13_proxy
  - istio_release-1.13_tools
  - istio_release-1.13_release-builder
- name: istio_release-1.12
  dashboard_names:
  - istio_release-1.12_istio_postsubmit
  - istio_release-1.12_client-go_postsubmit
  - istio_release-1.12_common-files_postsubmit
  - istio_release-1.12_gogo-genproto_postsubmit
  - istio_release-1.12_istio.io_postsubmit
  - istio_release-1.12_pkg_postsubmit
  - istio_release-1.12_proxy_postsubmit
  - istio_release-1.12_api_postsubmit
  - istio_release-1.12_tools_postsubmit
  - istio_release-1.12_release-builder_postsubmit
  - istio_release-1.12_istio
  - istio_release-1.12_api
  - istio_release-1.12_client-go
  - istio_release-1.12_common-files
  - istio_release-1.12_envoy
  - istio_release-1.12_gogo-genproto
  - istio_release-1.12_istio.io
  - istio_release-1.12_pkg
  - istio_release-1.12_proxy
  - istio_release-1.12_tools
  - istio_release-1.12_release-builder
- name: istio_release-1.11
  dashboard_names:
  - istio_release-1.11_istio_postsubmit
  - istio_release-1.11_client-go_postsubmit
  - istio_release-1.11_common-files_postsubmit
  - istio_release-1.11_gogo-genproto_postsubmit
  - istio_release-1.11_istio.io_postsubmit
  - istio_release-1.11_pkg_postsubmit
  - istio_release-1.11_proxy_postsubmit
  - istio_release-1.11_api_postsubmit
  - istio_release-1.11_tools_postsubmit
  - istio_release-1.11_release-builder_postsubmit
  - istio_release-1.11_istio
  - istio_release-1.11_api
  - istio_release-1.11_client-go
  - istio_release-1.11_common-files
  - istio_release-1.11_envoy
  - istio_release-1.11_gogo-genproto
  - istio_release-1.11_istio.io
  - istio_release-1.11_pkg
  - istio_release-1.11_proxy
  - istio_release-1.11_tools
  - istio_release-1.11_release-builder
- name: istio
  dashboard_names:
  - istio_istio.io_periodic
  - istio_test-infra_periodic
  - istio_istio_postsubmit
  - istio_istio_periodic
  - istio_api_postsubmit
  - istio_bots_postsubmit
  - istio_client-go_postsubmit
  - istio_cri_postsubmit
  - istio_common-files_postsubmit
  - istio_community_postsubmit
  - istio_istio.io_postsubmit
  - istio_pkg_postsubmit
  - istio_proxy_postsubmit
  - istio_test-infra_postsubmit
  - istio_tools_postsubmit
  - istio_istio
  - istio_api
  - istio_bots
  - istio_client-go
  - istio_cri
  - istio_common-files
  - istio_community
  - istio_envoy
  - istio_infrastructure
  - istio_istio.io
  - istio_pkg
  - istio_proxy
  - istio_proxy_periodic
  - istio_test-infra
  - istio_tools
