# basic config options.
http-cache-dir: /cache/httpcache
organization: istio
project: istio
pr-mungers: submit-queue
state: open
token-file: /etc/secret-volume/token
period: 1m
repo-dir: /gitrepos
github-key-file: /etc/hook-secret-volume/secret

# status context options.
required-contexts: "\
  ci/circleci: build,\
  ci/circleci: codecov,\
  ci/circleci: dependencies,\
  ci/circleci: e2e-pilot,\
  ci/circleci: e2e-pilot-noauth-v1alpha3-v2,\
  ci/circleci: e2e-pilot-cloudfoundry-v1alpha3-v2,\
  ci/circleci: e2e-simple,\
  ci/circleci: lint,\
  ci/circleci: racetest,\
  ci/circleci: test,\
  cla/google,\
  prow/e2e-bookInfoTests.sh,\
  prow/e2e-simpleTests.sh,\
  prow/istio-presubmit.sh"
protected-branches-extra-contexts: ""
required-retest-contexts: "\
  ci/circleci: build,\
  ci/circleci: codecov,\
  ci/circleci: dependencies,\
  ci/circleci: e2e-pilot,\
  ci/circleci: e2e-pilot-noauth-v1alpha3-v2,\
  ci/circleci: e2e-pilot-cloudfoundry-v1alpha3-v2,\
  ci/circleci: e2e-simple,\
  ci/circleci: lint,\
  ci/circleci: racetest,\
  ci/circleci: test,\
  cla/google,\
  prow/e2e-bookInfoTests.sh,\
  prow/e2e-simpleTests.sh,\
  prow/istio-presubmit.sh"

# submit-queue options.
protected-branches: "release-0.8"
nonblocking-jenkins-jobs: ""
do-not-merge-milestones: ""
admin-port: "9999"
prow-url: "https://prow.istio.io"
context-url: "http://35.197.104.17:8080"
merge-method: "squash"

# Temporary gate approval process
gate-cla: true
gate-approved: true

# Acceptable CLA label(s)
cla-yes-labels: "cla: yes,cla: human-approved"

blocking-labels: "do-not-merge/post-submit"
