defaults:
  branches:
  - release-1.10
  repo-allowlist:
  - istio.io
org: istio
repo: istio.io
transforms:
- job-denylist:
  - update-ref-docs-dry-run_istio.io_release-1.10
  job-type:
  - presubmit
  - postsubmit
