defaults:
  branches:
  - release-1.11
  repo-allowlist:
  - istio
org: istio
repo: istio
transforms:
- env:
    DOCKER_HUB: gcr.io/istio-prow-build
    GCS_BUCKET: istio-private-build/dev
  job-allowlist:
  - release_istio_release-1.11_postsubmit
  job-type:
  - postsubmit
  labels:
    preset-enable-netrc: "true"
    preset-enable-ssh: "true"
    preset-override-deps: release-1.11-istio
- job-denylist:
  - benchmark-report_istio_release-1.11_postsubmit
  - release_istio_release-1.11_postsubmit
  - release-notes_istio_release-1.11
  job-type:
  - presubmit
  - postsubmit
  labels:
    preset-enable-netrc: "true"
    preset-enable-ssh: "true"
    preset-override-deps: release-1.11-istio
    preset-override-envoy: "true"
