defaults:
  branches:
  - release-1.13
  repo-allowlist:
  - istio
org: istio
repo: istio
transforms:
- env:
    DOCKER_HUB: gcr.io/istio-prow-build
    GCS_BUCKET: istio-private-build/dev
    HELM_BUCKET: istio-private-build/dev/charts
  job-allowlist:
  - release_istio_release-1.13_postsubmit
  job-type:
  - postsubmit
  labels:
    preset-enable-gomod-netrc: "true"
    preset-enable-ssh: "true"
    preset-override-deps: release-1.13-istio
- job-denylist:
  - benchmark-report_istio_release-1.13_postsubmit
  - release_istio_release-1.13_postsubmit
  - release-notes_istio_release-1.13
  job-type:
  - presubmit
  - postsubmit
  labels:
    preset-enable-gomod-netrc: "true"
    preset-enable-ssh: "true"
    preset-override-deps: release-1.13-istio
    preset-override-envoy: "true"
