defaults:
  branches:
  - release-1.17
  modifier: release-1.17_priv
  repo-allowlist:
  - proxy
org: istio
repo: proxy
transforms:
- env:
    BAZEL_BUILD_RBE_INSTANCE: ""
    ENVOY_PREFIX: envoy
    ENVOY_REPOSITORY: https://github.com/istio-private/envoy
  job-denylist:
  - ".*arm64.*"
  job-type:
  - presubmit
  labels:
    preset-enable-netrc: "true"
- env:
    BAZEL_BUILD_RBE_INSTANCE: ""
    DOCKER_REPOSITORY: istio-prow-build/envoy
    ENVOY_PREFIX: envoy
    ENVOY_REPOSITORY: https://github.com/istio-private/envoy
    GCS_BUILD_BUCKET: istio-build-private
  job-denylist:
  - update-istio_proxy_release-1.17
  - ".*arm64.*"
  job-type:
  - postsubmit
  labels:
    preset-enable-netrc: "true"
- env:
    BAZEL_BUILD_RBE_INSTANCE: null
    GCS_BUILD_BUCKET: istio-build-private
    DOCKER_REPOSITORY: istio-prow-build/envoy
    ENVOY_REPOSITORY: https://github.com/istio-private/envoy
    ENVOY_PREFIX: envoy
  labels:
    preset-enable-netrc: "true"
  job-type: [presubmit, postsubmit]
  job-allowlist: [".*arm64.*"]
  cluster: "prow-arm-private"
