defaults:
  branches: [release-1.6]
  repo-whitelist: [proxy]
  modifier: release-1.6_priv


transforms:

# istio/proxy release-1.6 test jobs(s) - presubmit(s)
- env:
    BAZEL_BUILD_RBE_INSTANCE: projects/istio-prow-build/instances/default_instance
    ENVOY_REPOSITORY: https://github.com/istio-private/envoy
    ENVOY_PREFIX: envoy
  labels:
    preset-enable-netrc: "true"
  job-type: [presubmit]


# istio/proxy release-1.6 build jobs(s) - postsubmit(s)
- env:
    BAZEL_BUILD_RBE_INSTANCE: projects/istio-prow-build/instances/default_instance
    GCS_BUILD_BUCKET: istio-private-build
    GCS_ARTIFACTS_BUCKET: istio-private-artifacts
    DOCKER_REPOSITORY: istio-prow-build/envoy
    ENVOY_REPOSITORY: https://github.com/istio-private/envoy
    ENVOY_PREFIX: envoy
  labels:
    preset-enable-netrc: "true"
  job-type: [postsubmit]
