defaults:
  branches:
  - release-1.16
  modifier: release-1.16_priv
  repo-allowlist:
  - proxy
org: istio
repo: proxy
transforms:
- env:
    BAZEL_BUILD_RBE_INSTANCE: ""
    ENVOY_PREFIX: envoy
    ENVOY_REPOSITORY: https://github.com/istio-private/envoy
  job-type:
  - presubmit
  labels:
    preset-enable-netrc: "true"
- env:
    BAZEL_BUILD_RBE_INSTANCE: ""
    DOCKER_REPOSITORY: istio-prow-build/envoy
    ENVOY_PREFIX: envoy
    ENVOY_REPOSITORY: https://github.com/istio-private/envoy
    GCS_ARTIFACTS_BUCKET: istio-private-artifacts
    GCS_BUILD_BUCKET: istio-private-build
  job-denylist:
  - update-istio_proxy_release-1.16
  job-type:
  - postsubmit
  labels:
    preset-enable-netrc: "true"
