defaults:
  branches: [release-1.9]
  repo-allowlist: [release-builder]


transforms:

# istio/release-builder release-1.9 test jobs(s) - pre/postsubmit(s)
- job-type: [presubmit, postsubmit]
  repo-allowlist: [release-builder]
  job-allowlist: [lint_release-builder_release-1.9,lint_release-builder_release-1.9_postsubmit,test_release-builder_release-1.9,test_release-builder_release-1.9_postsubmit,gencheck_release-builder_release-1.9,gencheck_release-builder_release-1.9_postsubmit]
  labels:
    preset-use-go-control-plane-api-private: "true"
    preset-enable-netrc: "true"

# istio/release-builder release-1.9 build warning jobs(s) - presubmit(s)
- env:
    PRERELEASE_DOCKER_HUB: gcr.io/istio-prow-build
    GCS_BUCKET: istio-private-prerelease/prerelease
  job-type: [presubmit]
  repo-allowlist: [release-builder]
  job-allowlist: [build-warning_release-builder_release-1.9]

  # istio/release-builder release-1.9 build jobs(s) - postsubmit(s)
- env:
    PRERELEASE_DOCKER_HUB: gcr.io/istio-prow-build
    GCS_BUCKET: istio-private-prerelease/prerelease
  labels:
    preset-enable-ssh: "true"
    preset-override-envoy: "true"
    preset-override-deps: release-1.9-release
    preset-use-go-control-plane-api-private: "true"
    preset-enable-netrc: "true"
  job-type: [postsubmit]
  repo-allowlist: [release-builder]
  job-allowlist: [build-release_release-builder_release-1.9_postsubmit]
