defaults:
  branches: [release-1.10]
  repo-allowlist: [release-builder]


transforms:

# istio/release-builder test jobs(s) - pre/postsubmit(s)
- job-type: [presubmit, postsubmit]
  repo-allowlist: [release-builder]
  job-allowlist: [lint_release-builder_release-1.10,lint_release-builder_release-1.10_postsubmit,test_release-builder_release-1.10,test_release-builder_release-1.10_postsubmit,gencheck_release-builder_release-1.10,gencheck_release-builder_release-1.10_postsubmit]
  labels:

# istio/release-builder build warning jobs(s) - presubmit(s)
- env:
    PRERELEASE_DOCKER_HUB: gcr.io/istio-prow-build
    GCS_BUCKET: istio-private-prerelease/prerelease
  job-type: [presubmit]
  repo-allowlist: [release-builder]
  job-allowlist: [build-warning_release-builder_release-1.10]

  # istio/release-builder build jobs(s) - postsubmit(s)
- env:
    PRERELEASE_DOCKER_HUB: gcr.io/istio-prow-build
    GCS_BUCKET: istio-private-prerelease/prerelease
  labels:
    preset-enable-ssh: "true"
    preset-override-envoy: "true"
    preset-override-deps: release-1.10-release
  job-type: [postsubmit]
  repo-allowlist: [release-builder]
  job-allowlist: [build-release_release-builder_release-1.10_postsubmit]
