apiVersion: apps/v1
kind: Deployment
metadata:
  name: boskos-reaper
  labels:
    app: boskos-reaper
  namespace: boskos
spec:
  selector:
    matchLabels:
      app: boskos-reaper
  replicas: 1  # one canonical source of resources
  template:
    metadata:
      labels:
        app: boskos-reaper
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: boskos-reaper
        image: gcr.io/k8s-staging-boskos/reaper:v20200819-984516e
        args:
        - --resource-type=gke-perf-preset,gcp-perf-test-project,gcp-project,gke-e2e-test
      tolerations:
      - key: dedicated
        operator: Equal
        value: boskos
        effect: NoSchedule
      nodeSelector:
        prod: boskos

