branches:
- release-1.16
env:
- name: BUILD_WITH_CONTAINER
  value: "0"
- name: BUILD_WITH_CONTAINER
  value: "0"
image: gcr.io/istio-testing/build-tools:release-1.16-04bff0a4819cdfd500eb7817ed686f10c30b4456
jobs:
- command:
  - make
  - presubmit
  env:
  - name: BUILD_WITH_CONTAINER
    value: "0"
  image: gcr.io/istio-testing/build-tools:release-1.16-04bff0a4819cdfd500eb7817ed686f10c30b4456
  name: build
  node_selector:
    testing: test-pool
  requirement_presets:
    cache:
      volumeMounts:
      - mountPath: /home/prow/go/pkg
        name: build-cache
        subPath: gomod
      volumes:
      - hostPath:
          path: /var/tmp/prow/cache
          type: DirectoryOrCreate
        name: build-cache
    docker:
      volumeMounts:
      - mountPath: /var/lib/docker
        name: docker-root
      volumes:
      - emptyDir: {}
        name: docker-root
    github:
      volumeMounts:
      - mountPath: /etc/github-token
        name: github
        readOnly: true
      volumes:
      - name: github
        secret:
          secretName: oauth-token
    github-optional:
      volumeMounts:
      - mountPath: /etc/github-token
        name: github
        readOnly: true
      volumes:
      - name: github
        secret:
          optional: true
          secretName: oauth-token
    gocache:
      volumeMounts:
      - mountPath: /gocache
        name: build-cache
        subPath: gocache
      volumes:
      - hostPath:
          path: /var/tmp/prow/cache
          type: DirectoryOrCreate
        name: build-cache
    kind:
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
        readOnly: true
      - mountPath: /var/lib/docker
        name: docker-root
      volumes:
      - hostPath:
          path: /lib/modules
          type: Directory
        name: modules
      - hostPath:
          path: /sys/fs/cgroup
          type: Directory
        name: cgroup
      - emptyDir: {}
        name: docker-root

  requirements:
  - cache
  - cache
  resources_presets:
    default:
      limits:
        cpu: "3"
        memory: 24Gi
      requests:
        cpu: "1"
        memory: 3Gi
- command:
  - make
  - gen-check
  env:
  - name: BUILD_WITH_CONTAINER
    value: "0"
  image: gcr.io/istio-testing/build-tools:release-1.16-04bff0a4819cdfd500eb7817ed686f10c30b4456
  name: gencheck
  node_selector:
    testing: test-pool
  requirement_presets:
    cache:
      volumeMounts:
      - mountPath: /home/prow/go/pkg
        name: build-cache
        subPath: gomod
      volumes:
      - hostPath:
          path: /var/tmp/prow/cache
          type: DirectoryOrCreate
        name: build-cache
    docker:
      volumeMounts:
      - mountPath: /var/lib/docker
        name: docker-root
      volumes:
      - emptyDir: {}
        name: docker-root
    github:
      volumeMounts:
      - mountPath: /etc/github-token
        name: github
        readOnly: true
      volumes:
      - name: github
        secret:
          secretName: oauth-token
    github-optional:
      volumeMounts:
      - mountPath: /etc/github-token
        name: github
        readOnly: true
      volumes:
      - name: github
        secret:
          optional: true
          secretName: oauth-token
    gocache:
      volumeMounts:
      - mountPath: /gocache
        name: build-cache
        subPath: gocache
      volumes:
      - hostPath:
          path: /var/tmp/prow/cache
          type: DirectoryOrCreate
        name: build-cache
    kind:
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
        readOnly: true
      - mountPath: /var/lib/docker
        name: docker-root
      volumes:
      - hostPath:
          path: /lib/modules
          type: Directory
        name: modules
      - hostPath:
          path: /sys/fs/cgroup
          type: Directory
        name: cgroup
      - emptyDir: {}
        name: docker-root

  requirements:
  - cache
  - cache
  resources_presets:
    default:
      limits:
        cpu: "3"
        memory: 24Gi
      requests:
        cpu: "1"
        memory: 3Gi
- command:
  - entrypoint
  - ../test-infra/tools/automator/automator.sh
  - --org=istio
  - --repo=client-go
  - '--title=Automator: update istio/api@$AUTOMATOR_SRC_BRANCH dependency in $AUTOMATOR_ORG/$AUTOMATOR_REPO@$AUTOMATOR_BRANCH'
  - --labels=auto-merge,release-notes-none
  - --modifier=update_api_dep
  - --token-env
  - --cmd=go get istio.io/api@$AUTOMATOR_SHA && go mod tidy && make clean gen
  env:
  - name: BUILD_WITH_CONTAINER
    value: "0"
  image: gcr.io/istio-testing/build-tools:release-1.16-04bff0a4819cdfd500eb7817ed686f10c30b4456
  name: update-api-dep-client-go
  node_selector:
    testing: test-pool
  repos:
  - istio/test-infra@master
  requirement_presets:
    cache:
      volumeMounts:
      - mountPath: /home/prow/go/pkg
        name: build-cache
        subPath: gomod
      volumes:
      - hostPath:
          path: /var/tmp/prow/cache
          type: DirectoryOrCreate
        name: build-cache
    docker:
      volumeMounts:
      - mountPath: /var/lib/docker
        name: docker-root
      volumes:
      - emptyDir: {}
        name: docker-root
    github:
      volumeMounts:
      - mountPath: /etc/github-token
        name: github
        readOnly: true
      volumes:
      - name: github
        secret:
          secretName: oauth-token
    github-optional:
      volumeMounts:
      - mountPath: /etc/github-token
        name: github
        readOnly: true
      volumes:
      - name: github
        secret:
          optional: true
          secretName: oauth-token
    gocache:
      volumeMounts:
      - mountPath: /gocache
        name: build-cache
        subPath: gocache
      volumes:
      - hostPath:
          path: /var/tmp/prow/cache
          type: DirectoryOrCreate
        name: build-cache
    kind:
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
        readOnly: true
      - mountPath: /var/lib/docker
        name: docker-root
      volumes:
      - hostPath:
          path: /lib/modules
          type: Directory
        name: modules
      - hostPath:
          path: /sys/fs/cgroup
          type: Directory
        name: cgroup
      - emptyDir: {}
        name: docker-root

  requirements:
  - cache
  - cache
  - github-istio-testing
  resources_presets:
    default:
      limits:
        cpu: "3"
        memory: 24Gi
      requests:
        cpu: "1"
        memory: 3Gi
  types:
  - postsubmit
- command:
  - entrypoint
  - gen-release-notes
  - --checkLabel
  - --validateOnly
  env:
  - name: BUILD_WITH_CONTAINER
    value: "0"
  image: gcr.io/istio-testing/build-tools:release-1.16-04bff0a4819cdfd500eb7817ed686f10c30b4456
  modifiers:
  - presubmit_optional
  name: release-notes
  node_selector:
    testing: test-pool
  requirement_presets:
    cache:
      volumeMounts:
      - mountPath: /home/prow/go/pkg
        name: build-cache
        subPath: gomod
      volumes:
      - hostPath:
          path: /var/tmp/prow/cache
          type: DirectoryOrCreate
        name: build-cache
    docker:
      volumeMounts:
      - mountPath: /var/lib/docker
        name: docker-root
      volumes:
      - emptyDir: {}
        name: docker-root
    github:
      volumeMounts:
      - mountPath: /etc/github-token
        name: github
        readOnly: true
      volumes:
      - name: github
        secret:
          secretName: oauth-token
    github-optional:
      volumeMounts:
      - mountPath: /etc/github-token
        name: github
        readOnly: true
      volumes:
      - name: github
        secret:
          optional: true
          secretName: oauth-token
    gocache:
      volumeMounts:
      - mountPath: /gocache
        name: build-cache
        subPath: gocache
      volumes:
      - hostPath:
          path: /var/tmp/prow/cache
          type: DirectoryOrCreate
        name: build-cache
    kind:
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
        readOnly: true
      - mountPath: /var/lib/docker
        name: docker-root
      volumes:
      - hostPath:
          path: /lib/modules
          type: Directory
        name: modules
      - hostPath:
          path: /sys/fs/cgroup
          type: Directory
        name: cgroup
      - emptyDir: {}
        name: docker-root

  requirements:
  - cache
  - cache
  - github-readonly
  resources_presets:
    default:
      limits:
        cpu: "3"
        memory: 24Gi
      requests:
        cpu: "1"
        memory: 3Gi
  types:
  - presubmit
node_selector:
  testing: test-pool
org: istio
repo: api
requirement_presets:
  cache:
    volumeMounts:
    - mountPath: /home/prow/go/pkg
      name: build-cache
      subPath: gomod
    volumes:
    - hostPath:
        path: /var/tmp/prow/cache
        type: DirectoryOrCreate
      name: build-cache
  docker:
    volumeMounts:
    - mountPath: /var/lib/docker
      name: docker-root
    volumes:
    - emptyDir: {}
      name: docker-root
  github:
    volumeMounts:
    - mountPath: /etc/github-token
      name: github
      readOnly: true
    volumes:
    - name: github
      secret:
        secretName: oauth-token
  github-optional:
    volumeMounts:
    - mountPath: /etc/github-token
      name: github
      readOnly: true
    volumes:
    - name: github
      secret:
        optional: true
        secretName: oauth-token
  gocache:
    volumeMounts:
    - mountPath: /gocache
      name: build-cache
      subPath: gocache
    volumes:
    - hostPath:
        path: /var/tmp/prow/cache
        type: DirectoryOrCreate
      name: build-cache
  kind:
    volumeMounts:
    - mountPath: /lib/modules
      name: modules
      readOnly: true
    - mountPath: /sys/fs/cgroup
      name: cgroup
      readOnly: true
    - mountPath: /var/lib/docker
      name: docker-root
    volumes:
    - hostPath:
        path: /lib/modules
        type: Directory
      name: modules
    - hostPath:
        path: /sys/fs/cgroup
        type: Directory
      name: cgroup
    - emptyDir: {}
      name: docker-root

requirements:
- cache
- cache
resources_presets:
  default:
    limits:
      cpu: "3"
      memory: 24Gi
    requests:
      cpu: "1"
      memory: 3Gi
