branches:
- release-1.4
image: gcr.io/istio-testing/build-tools:release-1.4-2019-11-05T22-47-16
jobs:
- command:
  - make
  - build
  name: build
- command:
  - make
  - lint
  name: lint
- command:
  - make
  - gen-check
  name: gencheck
org: istio
repo: client-go
resources:
  default:
    limits:
      cpu: "3"
      memory: 24Gi
    requests:
      cpu: 500m
      memory: 3Gi
