branches:
- release-1.10
image: gcr.io/istio-testing/build-tools:release-1.10-2021-07-06T17-17-03
jobs:
- command:
  - make
  - build
  name: build
  node_selector:
    testing: test-pool
  requirements:
  - cache
- command:
  - make
  - lint
  name: lint
  node_selector:
    testing: test-pool
  requirements:
  - cache
- command:
  - make
  - gen-check
  name: gencheck
  node_selector:
    testing: test-pool
  requirements:
  - cache
org: istio
repo: client-go
requirement_presets:
  cache:
    env: null
    labels: null
    volumeMounts:
    - mountPath: /home/prow/go/pkg
      name: build-cache
      subPath: gomod
    volumes:
    - hostPath:
        path: /tmp/prow/cache
        type: DirectoryOrCreate
      name: build-cache
  deploy:
    env: null
    labels:
      preset-prow-deployer-service-account: "true"
    volumeMounts: null
    volumes: null
  docker:
    env: null
    labels: null
    volumeMounts:
    - mountPath: /var/lib/docker
      name: docker-root
    volumes:
    - emptyDir: {}
      name: docker-root
  gcp:
    env: null
    labels:
      preset-service-account: "true"
    volumeMounts: null
    volumes: null
  github:
    env: null
    labels: null
    volumeMounts:
    - mountPath: /etc/github-token
      name: github
      readOnly: true
    volumes:
    - name: github
      secret:
        secretName: oauth-token
  gocache:
    env: null
    labels: null
    volumeMounts:
    - mountPath: /gocache
      name: build-cache
      subPath: gocache
    volumes:
    - hostPath:
        path: /tmp/prow/cache
        type: DirectoryOrCreate
      name: build-cache
  kind:
    env: null
    labels: null
    volumeMounts:
    - mountPath: /lib/modules
      name: modules
      readOnly: true
    - mountPath: /sys/fs/cgroup
      name: cgroup
      readOnly: true
    - mountPath: /var/lib/docker
      name: docker-root
    volumes:
    - hostPath:
        path: /lib/modules
        type: Directory
      name: modules
    - hostPath:
        path: /sys/fs/cgroup
        type: Directory
      name: cgroup
    - emptyDir: {}
      name: docker-root
  release:
    env: null
    labels:
      preset-release-pipeline: "true"
    volumeMounts: null
    volumes: null
resources:
  default:
    limits:
      cpu: "3"
      memory: 24Gi
    requests:
      cpu: "1"
      memory: 3Gi
