org: istio
repo: cni
support_release_branching: true
image: gcr.io/istio-testing/build-tools:master-2020-04-01T21-36-34

jobs:
  - name: build
    command: [entrypoint, make, docker]

  - name: install
    command: [entrypoint, make, docker, test]

  - name: lint
    command: [make, lint]

  - name: gencheck
    command: [make, gen-check]
