org: istio
repo: cni
branches:
  - master

jobs:
  - name: build
    command: [make, docker]
  - name: install
    command: [make, docker, test]
  - name: e2e
    command: [make, prow-e2e]
    requirements: [kind]
    repos: [istio/istio]

  - name: buildmodern
    command: [make, docker]
    image: gcr.io/istio-testing/build-tools:2019-09-17T18-24-15
    suppress_entrypoint: true
    modifiers: [optional]

  - name: lintmodern
    command: [make, lint_modern]
    image: gcr.io/istio-testing/build-tools:2019-09-17T18-24-15
    suppress_entrypoint: true
