org: istio
repo: cni
image: gcr.io/istio-testing/build-tools:2019-10-10T00-49-39

branches:
  - master

jobs:
  - name: build
    command: [make, docker]

  - name: test
    command: [make, test]

  - name: e2e
    command: [make, e2e]
    requirements: [kind]
    repos: [istio/istio]

  - name: lint
    command: [make, lint]
