org: istio
repo: cni
support_release_branching: true
image:gcr.io/istio-testing/build-tools:master-2019-12-03T17-07-58

jobs:
  - name: build
    command: [entrypoint, make, docker]

  - name: install
    command: [entrypoint, make, docker, test]

  - name: e2e
    command: [entrypoint, make, e2e]
    requirements: [kind]
    repos: [istio/istio]

  - name: lint
    command: [make, lint]

  - name: gencheck
    command: [make, gen-check]
