branches:
- release-1.11
image: gcr.io/istio-testing/build-tools:release-1.11-2021-10-12T18-10-18
jobs:
- command:
  - make
  - lint
  image: gcr.io/istio-testing/build-tools:release-1.11-2021-10-12T18-10-18
  name: lint
  node_selector:
    testing: test-pool
  requirements:
  - cache
- command:
  - ../test-infra/tools/automator/automator.sh
  - --org=istio
  - --repo=istio,api,tools,release-builder,pkg,client-go,gogo-genproto,proxy
  - '--title=Automator: update common-files@$AUTOMATOR_SRC_BRANCH in $AUTOMATOR_ORG/$AUTOMATOR_REPO@$AUTOMATOR_BRANCH'
  - --labels=auto-merge,release-notes-none
  - --strict
  - --modifier=commonfiles
  - --token-path=/etc/github-token/oauth
  - --cmd=make update-common && make gen
  image: gcr.io/istio-testing/build-tools:release-1.11-2021-10-12T18-10-18
  name: update-common
  node_selector:
    testing: test-pool
  repos:
  - istio/test-infra@master
  requirements:
  - cache
  - github
  types:
  - postsubmit
- command:
  - ../test-infra/tools/automator/automator.sh
  - --org=istio
  - --repo=istio.io
  - '--title=Automator: update common-files@$AUTOMATOR_SRC_BRANCH in $AUTOMATOR_ORG/$AUTOMATOR_REPO@$AUTOMATOR_BRANCH'
  - --labels=auto-merge,release-notes-none
  - --strict
  - --modifier=commonfiles
  - --token-path=/etc/github-token/oauth
  - --cmd=make update-common && make gen
  image: gcr.io/istio-testing/build-tools:release-1.11-2021-10-12T18-10-18
  name: update-common-istio.io
  node_selector:
    testing: test-pool
  repos:
  - istio/test-infra@master
  requirements:
  - cache
  - github
  types:
  - postsubmit
- command:
  - ../test-infra/tools/automator/automator.sh
  - --org=istio
  - --repo=test-infra
  - '--title=Automator: update build-tools:$AUTOMATOR_SRC_BRANCH'
  - --branch=master
  - --modifier=buildtools
  - --token-path=/etc/github-token/oauth
  - --script-path=../test-infra/tools/automator/scripts/update-images.sh
  - --labels=release-notes-none
  - --verbose
  - --
  - --post=make gen
  - --source=$AUTOMATOR_ROOT_DIR/files/common/scripts/setup_env.sh
  image: gcr.io/istio-testing/build-tools:release-1.11-2021-10-12T18-10-18
  name: update-build-tools-image
  node_selector:
    testing: test-pool
  repos:
  - istio/test-infra@master
  requirements:
  - cache
  - github
  types:
  - postsubmit
org: istio
repo: common-files
requirement_presets:
  cache:
    annotations: null
    env: null
    labels: null
    volumeMounts:
    - mountPath: /home/prow/go/pkg
      name: build-cache
      subPath: gomod
    volumes:
    - hostPath:
        path: /var/tmp/prow/cache
        type: DirectoryOrCreate
      name: build-cache
  docker:
    annotations: null
    env: null
    labels: null
    volumeMounts:
    - mountPath: /var/lib/docker
      name: docker-root
    volumes:
    - emptyDir: {}
      name: docker-root
  gcp:
    annotations: null
    env: null
    labels:
      preset-service-account: "true"
    volumeMounts: null
    volumes: null
  github:
    annotations: null
    env: null
    labels: null
    volumeMounts:
    - mountPath: /etc/github-token
      name: github
      readOnly: true
    volumes:
    - name: github
      secret:
        secretName: oauth-token
  github-optional:
    annotations: null
    env: null
    labels: null
    volumeMounts:
    - mountPath: /etc/github-token
      name: github
      readOnly: true
    volumes:
    - name: github
      secret:
        optional: true
        secretName: oauth-token
  gocache:
    annotations: null
    env: null
    labels: null
    volumeMounts:
    - mountPath: /gocache
      name: build-cache
      subPath: gocache
    volumes:
    - hostPath:
        path: /var/tmp/prow/cache
        type: DirectoryOrCreate
      name: build-cache
  kind:
    annotations: null
    env: null
    labels: null
    volumeMounts:
    - mountPath: /lib/modules
      name: modules
      readOnly: true
    - mountPath: /sys/fs/cgroup
      name: cgroup
      readOnly: true
    - mountPath: /var/lib/docker
      name: docker-root
    volumes:
    - hostPath:
        path: /lib/modules
        type: Directory
      name: modules
    - hostPath:
        path: /sys/fs/cgroup
        type: Directory
      name: cgroup
    - emptyDir: {}
      name: docker-root
  release:
    annotations: null
    env: null
    labels:
      preset-release-pipeline: "true"
    volumeMounts: null
    volumes: null
resources_presets:
  default:
    limits:
      cpu: "3"
      memory: 24Gi
    requests:
      cpu: "1"
      memory: 3Gi
