branches:
- release-1.5
image: gcr.io/istio-testing/build-tools:release-1.5-2020-03-24T16-54-03
jobs:
- command:
  - make
  - lint
  name: lint
- command:
  - ../test-infra/tools/automator/automator.sh
  - --org=istio
  - --repo=istio,istio.io,api,test-infra,tools,bots,release-builder,pkg,cni,cri,client-go,gogo-genproto,proxy
  - '--title=Automator: update common-files@$AUTOMATOR_BRANCH in $AUTOMATOR_ORG/$AUTOMATOR_REPO@$AUTOMATOR_BRANCH'
  - --labels=auto-merge
  - --modifier=commonfiles
  - --token-path=/etc/github-token/oauth
  - --cmd=make update-common gen
  name: update-common
  repos:
  - istio/test-infra@master
  requirements:
  - github
  type: postsubmit
- name: update-build-tools-image
  type: postsubmit
  command:
  - ../test-infra/tools/automator/automator.sh
  - --org=istio
  - --repo=test-infra
  - --branch=master
  - "--title=Automator: update build-tools:$AUTOMATOR_BRANCH"
  - --modifier=buildtools
  - --token-path=/etc/github-token/oauth
  - --script-path=../test-infra/tools/automator/scripts/update-build-tools-image.sh
  - --
  - --post=make gen
  - --var=IMG
  requirements: [github]
  repos: [istio/test-infra@master]
org: istio
repo: common-files
resources:
  default:
    limits:
      cpu: "3"
      memory: 24Gi
    requests:
      cpu: 500m
      memory: 3Gi
