branches:
- release-1.15
env:
- name: BUILD_WITH_CONTAINER
  value: "0"
- name: BUILD_WITH_CONTAINER
  value: "0"
image: gcr.io/istio-testing/build-tools:release-1.15-d0c223ae98e58a729b936479ce956c5a8707fe3c
jobs:
- command:
  - ../test-infra/scripts/validate_schema.sh
  - --document-path=./features.yaml
  - --schema-path=./features_schema.json
  env:
  - name: BUILD_WITH_CONTAINER
    value: "0"
  - name: BUILD_WITH_CONTAINER
    value: "0"
  image: gcr.io/istio-testing/build-tools:release-1.15-d0c223ae98e58a729b936479ce956c5a8707fe3c
  modifiers:
  - presubmit_optional
  name: validate-features
  node_selector:
    testing: test-pool
  repos:
  - istio/test-infra@master
  - istio/tools@master
  requirement_presets:
    cache:
      volumeMounts:
      - mountPath: /home/prow/go/pkg
        name: build-cache
        subPath: gomod
      volumes:
      - hostPath:
          path: /var/tmp/prow/cache
          type: DirectoryOrCreate
        name: build-cache
    docker:
      volumeMounts:
      - mountPath: /var/lib/docker
        name: docker-root
      volumes:
      - emptyDir: {}
        name: docker-root
    github:
      volumeMounts:
      - mountPath: /etc/github-token
        name: github
        readOnly: true
      volumes:
      - name: github
        secret:
          secretName: oauth-token
    github-optional:
      volumeMounts:
      - mountPath: /etc/github-token
        name: github
        readOnly: true
      volumes:
      - name: github
        secret:
          optional: true
          secretName: oauth-token
    gocache:
      volumeMounts:
      - mountPath: /gocache
        name: build-cache
        subPath: gocache
      volumes:
      - hostPath:
          path: /var/tmp/prow/cache
          type: DirectoryOrCreate
        name: build-cache
    kind:
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
        readOnly: true
      - mountPath: /var/lib/docker
        name: docker-root
      volumes:
      - hostPath:
          path: /lib/modules
          type: Directory
        name: modules
      - hostPath:
          path: /sys/fs/cgroup
          type: Directory
        name: cgroup
      - emptyDir: {}
        name: docker-root
    release:
      env:
      - name: COSIGN_KEY
        valueFrom:
          secretKeyRef:
            key: key
            name: cosign-key
      - name: DOCKER_CONFIG
        value: /etc/rel-pipeline-docker-config
      - name: GITHUB_TOKEN_FILE
        value: /etc/github/rel-pipeline-github
      - name: GRAFANA_TOKEN_FILE
        value: /etc/grafana/token
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/service-account/rel-pipeline-service-account.json
      volumeMounts:
      - mountPath: /etc/rel-pipeline-docker-config
        name: rel-pipeline-docker-config
      - mountPath: /etc/github
        name: rel-pipeline-github
        readOnly: true
      - mountPath: /etc/grafana
        name: rel-pipeline-grafana
        readOnly: true
      - mountPath: /etc/service-account
        name: rel-pipeline-service-account
        readOnly: true
      volumes:
      - name: rel-pipeline-service-account
        secret:
          secretName: rel-pipeline-service-account
      - name: rel-pipeline-github
        secret:
          secretName: rel-pipeline-github
      - name: rel-pipeline-grafana
        secret:
          secretName: grafana-token
      - name: rel-pipeline-docker-config
        secret:
          secretName: rel-pipeline-docker-config
  requirements:
  - cache
  - cache
  resources_presets:
    default:
      limits:
        cpu: "3"
        memory: 24Gi
      requests:
        cpu: "1"
        memory: 3Gi
  types:
  - presubmit
node_selector:
  testing: test-pool
org: istio
repo: enhancements
requirement_presets:
  cache:
    volumeMounts:
    - mountPath: /home/prow/go/pkg
      name: build-cache
      subPath: gomod
    volumes:
    - hostPath:
        path: /var/tmp/prow/cache
        type: DirectoryOrCreate
      name: build-cache
  docker:
    volumeMounts:
    - mountPath: /var/lib/docker
      name: docker-root
    volumes:
    - emptyDir: {}
      name: docker-root
  github:
    volumeMounts:
    - mountPath: /etc/github-token
      name: github
      readOnly: true
    volumes:
    - name: github
      secret:
        secretName: oauth-token
  github-optional:
    volumeMounts:
    - mountPath: /etc/github-token
      name: github
      readOnly: true
    volumes:
    - name: github
      secret:
        optional: true
        secretName: oauth-token
  gocache:
    volumeMounts:
    - mountPath: /gocache
      name: build-cache
      subPath: gocache
    volumes:
    - hostPath:
        path: /var/tmp/prow/cache
        type: DirectoryOrCreate
      name: build-cache
  kind:
    volumeMounts:
    - mountPath: /lib/modules
      name: modules
      readOnly: true
    - mountPath: /sys/fs/cgroup
      name: cgroup
      readOnly: true
    - mountPath: /var/lib/docker
      name: docker-root
    volumes:
    - hostPath:
        path: /lib/modules
        type: Directory
      name: modules
    - hostPath:
        path: /sys/fs/cgroup
        type: Directory
      name: cgroup
    - emptyDir: {}
      name: docker-root
  release:
    env:
    - name: COSIGN_KEY
      valueFrom:
        secretKeyRef:
          key: key
          name: cosign-key
    - name: DOCKER_CONFIG
      value: /etc/rel-pipeline-docker-config
    - name: GITHUB_TOKEN_FILE
      value: /etc/github/rel-pipeline-github
    - name: GRAFANA_TOKEN_FILE
      value: /etc/grafana/token
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /etc/service-account/rel-pipeline-service-account.json
    volumeMounts:
    - mountPath: /etc/rel-pipeline-docker-config
      name: rel-pipeline-docker-config
    - mountPath: /etc/github
      name: rel-pipeline-github
      readOnly: true
    - mountPath: /etc/grafana
      name: rel-pipeline-grafana
      readOnly: true
    - mountPath: /etc/service-account
      name: rel-pipeline-service-account
      readOnly: true
    volumes:
    - name: rel-pipeline-service-account
      secret:
        secretName: rel-pipeline-service-account
    - name: rel-pipeline-github
      secret:
        secretName: rel-pipeline-github
    - name: rel-pipeline-grafana
      secret:
        secretName: grafana-token
    - name: rel-pipeline-docker-config
      secret:
        secretName: rel-pipeline-docker-config
requirements:
- cache
- cache
resources_presets:
  default:
    limits:
      cpu: "3"
      memory: 24Gi
    requests:
      cpu: "1"
      memory: 3Gi
