branches:
- release-1.6
image: gcr.io/istio-testing/build-tools:release-1.6-2020-05-08T22-06-04
jobs:
- command:
  - make
  - build
  name: build
- command:
  - make
  - lint
  name: lint
- command:
  - make
  - gen-check
  name: gencheck
org: istio
repo: gogo-genproto
resources:
  default:
    limits:
      cpu: "3"
      memory: 24Gi
    requests:
      cpu: 500m
      memory: 3Gi
