org: istio
repo: installer
support_release_branching: true
image: gcr.io/istio-testing/build-tools:master-2019-12-18T18-07-47

jobs:
  - name: build
    command: [make, run-build]

  - name: lint
    command: [make, lint_modern]

  - name: demo
    command: [entrypoint, bin/with-kind.sh, make, run-test-demo]
    requirements: [kind]
    repos: [istio/istio]

  - name: noauth
    command: [entrypoint, bin/with-kind.sh, make, run-test-noauth]
    requirements: [kind]
    repos: [istio/istio]

  - name: base
    command: [entrypoint, bin/with-kind.sh, make, run-base-reachability]
    requirements: [kind]
    repos: [istio/istio]

  - name: multi-namespace
    command: [entrypoint, bin/with-kind.sh, make, run-multinamespace]
    requirements: [kind]
    repos: [istio/istio]

  - name: gencheck
    command: [make, gen-check]
