branches:
- release-1.7
image: gcr.io/istio-testing/build-tools:release-1.7-2020-11-25T22-57-38
jobs:
- command:
  - make
  - lint
  name: lint
- command:
  - make
  - gen-check
  name: gencheck
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.kube.presubmit
  modifiers:
  - optional
  name: k8s-tests
  requirements:
  - kind
- command:
  - ../test-infra/tools/automator/automator.sh
  - --org=istio
  - --repo=istio.io
  - --token-path=/etc/github-token/oauth
  - --cmd=make update_ref_docs
  - --dry-run
  modifiers:
  - optional
  name: update-ref-docs-dry-run
  repos:
  - istio/test-infra@master
  requirements:
  - github
  types: [presubmit]
org: istio
repo: istio.io
resources:
  default:
    limits:
      cpu: "8"
      memory: 24Gi
    requests:
      cpu: "5"
      memory: 3Gi
  lint:
    limits:
      cpu: "5"
      memory: 24Gi
    requests:
      cpu: "3"
      memory: 16Gi
