branches:
- release-1.6
image: gcr.io/istio-testing/build-tools:release-1.6-2020-11-13T15-30-50
jobs:
- command:
  - entrypoint
  - make
  - -e
  - T=-v
  - build
  - racetest
  - binaries-test
  name: unit-tests
- command:
  - entrypoint
  - prow/release-test.sh
  name: release-test
  requirements:
  - gcp
  - docker
  types: [presubmit]
- command:
  - entrypoint
  - prow/release-commit.sh
  name: release
  requirements:
  - gcp
  - docker
  types: [postsubmit]
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.galley.kube.presubmit
  env:
  - name: TEST_SELECT
    value: -postsubmit,-flaky,-multicluster
  name: integ-galley-k8s-tests
  requirements:
  - kind
  types: [presubmit]
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.mixer.kube.presubmit
  env:
  - name: TEST_SELECT
    value: -postsubmit,-flaky,-multicluster
  name: integ-mixer-k8s-tests
  requirements:
  - kind
  types: [presubmit]
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.pilot.kube.presubmit
  env:
  - name: TEST_SELECT
    value: -postsubmit,-flaky,-multicluster
  name: integ-pilot-k8s-tests
  requirements:
  - kind
  types: [presubmit]
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.security.kube.presubmit
  env:
  - name: TEST_SELECT
    value: -postsubmit,-flaky,-multicluster
  name: integ-security-k8s-tests
  requirements:
  - kind
  types: [presubmit]
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.telemetry.kube.presubmit
  env:
  - name: TEST_SELECT
    value: -postsubmit,-flaky,-multicluster
  name: integ-telemetry-k8s-tests
  requirements:
  - kind
  types: [presubmit]
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - --topology
  - MULTICLUSTER_SINGLE_NETWORK
  - test.integration.kube.presubmit
  env:
  - name: TEST_SELECT
    value: -postsubmit,-flaky,+multicluster
  name: integ-multicluster-k8s-tests
  requirements:
  - kind
  types: [presubmit]
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.kube.reachability
  env:
  - name: VARIANT
    value: distroless
  - name: TEST_SELECT
    value: -multicluster
  name: integ-distroless-k8s-tests
  requirements:
  - kind
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.conformance.kube.presubmit
  env:
  - name: TEST_SELECT
    value: -postsubmit,-flaky,-multicluster
  name: integ-conformance-k8s-tests
  requirements:
  - kind
  types: [presubmit]
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.operator.kube.presubmit
  env:
  - name: TEST_SELECT
    value: -postsubmit,-flaky,-multicluster
  modifiers:
  - optional
  - hidden
  name: integ-operator-controller-tests
  requirements:
  - kind
  types: [presubmit]
- command:
  - entrypoint
  - prow/integ-suite-local.sh
  - test.integration...local
  env:
  - name: TEST_SELECT
    value: -multicluster
  name: integ-local-tests
  requirements:
  - docker
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.galley.kube
  env:
  - name: TEST_SELECT
    value: -multicluster
  name: integ-galley-k8s-tests
  requirements:
  - kind
  types: [postsubmit]
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.mixer.kube
  env:
  - name: TEST_SELECT
    value: -multicluster
  name: integ-mixer-k8s-tests
  requirements:
  - kind
  types: [postsubmit]
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.pilot.kube
  env:
  - name: TEST_SELECT
    value: -multicluster
  name: integ-pilot-k8s-tests
  requirements:
  - kind
  types: [postsubmit]
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.security.kube
  env:
  - name: TEST_SELECT
    value: -multicluster
  name: integ-security-k8s-tests
  requirements:
  - kind
  types: [postsubmit]
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.telemetry.kube
  env:
  - name: TEST_SELECT
    value: -multicluster
  name: integ-telemetry-k8s-tests
  requirements:
  - kind
  types: [postsubmit]
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.conformance.kube
  env:
  - name: TEST_SELECT
    value: -multicluster
  name: integ-conformance-k8s-tests
  requirements:
  - kind
  types: [postsubmit]
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - --node-image
  - kindest/node:v1.15.7
  - test.integration.kube.presubmit
  env:
  - name: INTEGRATION_TEST_FLAGS
    value: ' --istio.test.retries=1 '
  - name: TEST_SELECT
    value: -multicluster
  name: integ-k8s-115
  requirements:
  - kind
  timeout: 4h0m0s
  types: [postsubmit]
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - --node-image
  - kindest/node:v1.16.4
  - test.integration.kube.presubmit
  env:
  - name: INTEGRATION_TEST_FLAGS
    value: ' --istio.test.retries=1 '
  - name: TEST_SELECT
    value: -multicluster
  name: integ-k8s-116
  requirements:
  - kind
  timeout: 4h0m0s
  types: [postsubmit]
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - --node-image
  - kindest/node:v1.17.2
  - test.integration.kube.presubmit
  env:
  - name: INTEGRATION_TEST_FLAGS
    value: ' --istio.test.retries=1 '
  name: integ-k8s-117
  requirements:
  - kind
  timeout: 4h0m0s
  types: [postsubmit]
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - --node-image
  - gcr.io/istio-testing/kind-node:v1.19.0-alpha.1
  - test.integration.kube.presubmit
  env:
  - name: INTEGRATION_TEST_FLAGS
    value: ' --istio.test.retries=1 '
  modifiers:
  - hidden
  name: integ-k8s-119
  requirements:
  - kind
  timeout: 4h0m0s
  types: [postsubmit]
- command:
  - make
  - lint
  name: lint
  resources: lint
  types: [presubmit]
- command:
  - make
  - gen-check
  name: gencheck
  types: [presubmit]
org: istio
repo: istio
resources:
  default:
    limits:
      memory: 24Gi
    requests:
      cpu: "5"
      memory: 3Gi
  lint:
    limits:
      memory: 24Gi
    requests:
      cpu: "3"
      memory: 16Gi
