branches:
- release-1.9
image: gcr.io/istio-testing/build-tools:release-1.9-2021-09-09T06-24-57
jobs:
- command:
  - entrypoint
  - make
  - -e
  - T=-v -count=1
  - build
  - racetest
  - binaries-test
  name: unit-tests
- command:
  - entrypoint
  - prow/release-test.sh
  name: release-test
  service_account_name: prowjob-advanced-sa
  requirements:
  - docker
  types:
  - presubmit
- command:
  - entrypoint
  - prow/release-commit.sh
  name: release
  service_account_name: prowjob-advanced-sa
  requirements:
  - docker
  types:
  - postsubmit
- command:
  - entrypoint
  - make
  - benchtest
  modifiers:
  - presubmit_optional
  - presubmit_skipped
  name: benchmark
  resources: benchmark
  types:
  - presubmit
- command:
  - entrypoint
  - make
  - benchtest
  - report-benchtest
  name: benchmark-report
  service_account_name: prowjob-advanced-sa
  resources: benchmark
  types:
  - postsubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.pilot.kube.presubmit
  env:
  - name: TEST_SELECT
    value: -postsubmit,-flaky,-multicluster
  name: integ-pilot
  requirements:
  - kind
  types:
  - presubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.security.kube.presubmit
  env:
  - name: TEST_SELECT
    value: -postsubmit,-flaky,-multicluster
  name: integ-security
  requirements:
  - kind
  types:
  - presubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.telemetry.kube.presubmit
  env:
  - name: TEST_SELECT
    value: -postsubmit,-flaky,-multicluster
  name: integ-telemetry
  requirements:
  - kind
  types:
  - presubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - --topology
  - MULTICLUSTER
  - test.integration.telemetry.kube
  env:
  - name: TEST_SELECT
    value: -multicluster
  modifiers:
  - presubmit_optional
  name: integ-telemetry-mc
  requirements:
  - kind
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - --topology
  - MULTICLUSTER
  - test.integration.multicluster.kube.presubmit
  env:
  - name: TEST_SELECT
    value: -postsubmit,-flaky,+multicluster
  name: integ-multicluster
  requirements:
  - kind
  types:
  - presubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.kube.reachability
  env:
  - name: VARIANT
    value: distroless
  - name: TEST_SELECT
    value: -multicluster
  name: integ-distroless
  requirements:
  - kind
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.kube.reachability
  env:
  - name: DOCKER_IN_DOCKER_IPV6_ENABLED
    value: "true"
  - name: IP_FAMILY
    value: ipv6
  - name: TEST_SELECT
    value: -multicluster
  name: integ-ipv6
  requirements:
  - kind
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.operator.kube.presubmit
  env:
  - name: TEST_SELECT
    value: -postsubmit,-flaky,-multicluster
  name: integ-operator-controller
  requirements:
  - kind
  types:
  - presubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.pilot.kube
  env:
  - name: TEST_SELECT
    value: -multicluster
  name: integ-pilot
  requirements:
  - kind
  types:
  - postsubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - --topology
  - MULTICLUSTER
  - test.integration.pilot.kube
  env:
  - name: TEST_SELECT
    value: -multicluster
  name: integ-pilot-multicluster
  requirements:
  - kind
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.security.kube
  env:
  - name: TEST_SELECT
    value: -multicluster
  name: integ-security
  requirements:
  - kind
  types:
  - postsubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - --topology
  - MULTICLUSTER
  - test.integration.security.kube
  env:
  - name: TEST_SELECT
    value: -multicluster
  modifiers:
  - presubmit_optional
  name: integ-security-multicluster
  requirements:
  - kind
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.telemetry.kube
  env:
  - name: TEST_SELECT
    value: -multicluster
  name: integ-telemetry
  requirements:
  - kind
  types:
  - postsubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.helm.kube
  name: integ-helm
  requirements:
  - kind
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - --node-image
  - kindest/node:v1.15.12
  - test.integration.kube.presubmit
  env:
  - name: INTEGRATION_TEST_FLAGS
    value: ' --istio.test.retries=1 '
  name: integ-k8s-115
  requirements:
  - kind
  timeout: 4h0m0s
  types:
  - postsubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - --node-image
  - kindest/node:v1.16.15
  - test.integration.kube.presubmit
  env:
  - name: INTEGRATION_TEST_FLAGS
    value: ' --istio.test.retries=1 '
  name: integ-k8s-116
  requirements:
  - kind
  timeout: 4h0m0s
  types:
  - postsubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - --node-image
  - kindest/node:v1.17.11
  - --kind-config
  - prow/config/endpointslice.yaml
  - test.integration.kube.presubmit
  env:
  - name: INTEGRATION_TEST_FLAGS
    value: ' --istio.test.retries=1 '
  name: integ-k8s-117
  requirements:
  - kind
  timeout: 4h0m0s
  types:
  - postsubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - --node-image
  - kindest/node:v1.18.8
  - test.integration.kube.presubmit
  env:
  - name: INTEGRATION_TEST_FLAGS
    value: ' --istio.test.retries=1 '
  name: integ-k8s-118
  requirements:
  - kind
  timeout: 4h0m0s
  types:
  - postsubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - --node-image
  - kindest/node:v1.19.4
  - test.integration.kube.presubmit
  env:
  - name: INTEGRATION_TEST_FLAGS
    value: ' --istio.test.retries=1 '
  name: integ-k8s-119
  requirements:
  - kind
  timeout: 4h0m0s
  types:
  - postsubmit
- command:
  - make
  - test.integration.analyze
  name: analyze-tests
  types:
  - presubmit
- command:
  - make
  - lint
  name: lint
  resources: lint
  types:
  - presubmit
- command:
  - make
  - gen-check
  name: gencheck
  types:
  - presubmit
- command:
  - ../test-infra/tools/check_release_notes.sh
  - --token-path=/etc/github-token/oauth
  name: release-notes
  repos:
  - istio/test-infra@master
  - istio/tools@master
  requirements:
  - github-optional
  types:
  - presubmit
org: istio
repo: istio
requirements:
- gocache
resources_presets:
  benchmark:
    limits:
      memory: 24Gi
    requests:
      cpu: "15"
      memory: 8Gi
  default:
    limits:
      memory: 24Gi
    requests:
      cpu: "5"
      memory: 3Gi
  lint:
    limits:
      memory: 24Gi
    requests:
      cpu: "3"
      memory: 16Gi
