branches:
- release-1.5
image: gcr.io/istio-testing/build-tools:release-1.5-2020-02-14T14-00-07
jobs:
- command:
  - make
  - lint
  name: lint
org: istio
repo: istio.io
resources:
  default:
    limits:
      cpu: "3"
      memory: 24Gi
    requests:
      cpu: 500m
      memory: 3Gi
