branches:
- release-1.11
image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
jobs:
- command:
  - entrypoint
  - make
  - -e
  - T=-v -count=1
  - build
  - racetest
  - binaries-test
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  name: unit-tests
  node_selector:
    testing: test-pool
  requirements:
  - cache
  - gocache
- command:
  - entrypoint
  - prow/release-test.sh
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  name: release-test
  service_account_name: prowjob-advanced-sa
  node_selector:
    testing: test-pool
  requirements:
  - cache
  - docker
  - gocache
  types:
  - presubmit
- command:
  - entrypoint
  - prow/release-commit.sh
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  name: release
  service_account_name: prowjob-advanced-sa
  node_selector:
    testing: test-pool
  requirements:
  - cache
  - docker
  - gocache
  types:
  - postsubmit
- command:
  - entrypoint
  - make
  - benchtest
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  modifiers:
  - presubmit_optional
  - presubmit_skipped
  name: benchmark
  node_selector:
    testing: test-pool
  requirements:
  - cache
  - gocache
  resources: benchmark
  types:
  - presubmit
- command:
  - entrypoint
  - make
  - benchtest
  - report-benchtest
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  name: benchmark-report
  service_account_name: prowjob-advanced-sa
  node_selector:
    testing: test-pool
  requirements:
  - cache
  - gocache
  resources: benchmark
  types:
  - postsubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.pilot.kube.presubmit
  env:
  - name: TEST_SELECT
    value: -postsubmit,-flaky,-multicluster
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  name: integ-pilot
  node_selector:
    testing: test-pool
  requirements:
  - cache
  - kind
  - gocache
  types:
  - presubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.pilot.kube.presubmit
  env:
  - name: TEST_SELECT
    value: -postsubmit,-flaky,-multicluster
  - name: INTEGRATION_TEST_FLAGS
    value: ' --istio.test.istio.enableCNI=true '
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  name: integ-cni
  node_selector:
    testing: test-pool
  requirements:
  - cache
  - kind
  - gocache
  types:
  - presubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.security.kube.presubmit
  env:
  - name: TEST_SELECT
    value: -postsubmit,-flaky,-multicluster
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  name: integ-security
  node_selector:
    testing: test-pool
  requirements:
  - cache
  - kind
  - gocache
  types:
  - presubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.telemetry.kube.presubmit
  env:
  - name: TEST_SELECT
    value: -postsubmit,-flaky,-multicluster
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  name: integ-telemetry
  node_selector:
    testing: test-pool
  requirements:
  - cache
  - kind
  - gocache
  types:
  - presubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - --topology
  - MULTICLUSTER
  - test.integration.telemetry.kube
  env:
  - name: TEST_SELECT
    value: -multicluster
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  name: integ-telemetry-multicluster
  node_selector:
    testing: test-pool
  requirements:
  - cache
  - kind
  - gocache
  resources: multicluster
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - --topology
  - MULTICLUSTER
  - test.integration.telemetry.kube
  env:
  - name: TEST_SELECT
    value: -multicluster
  - name: INTEGRATION_TEST_FLAGS
    value: --istio.test.istio.istiodlessRemotes
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  modifiers:
  - presubmit_optional
  - presubmit_skipped
  - hidden
  name: integ-telemetry-istiodless-mc
  node_selector:
    testing: test-pool
  requirements:
  - cache
  - kind
  - gocache
  resources: multicluster
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - --topology
  - MULTICLUSTER
  - test.integration.multicluster.kube.presubmit
  env:
  - name: TEST_SELECT
    value: -postsubmit,-flaky,+multicluster
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  name: integ-multicluster
  node_selector:
    testing: test-pool
  requirements:
  - cache
  - kind
  - gocache
  resources: multicluster
  types:
  - presubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - --topology
  - MULTICLUSTER
  - --topology-config
  - prow/config/topology/external-istiod.json
  - test.integration.istiodremote.kube.presubmit
  env:
  - name: TEST_SELECT
    value: -postsubmit,-flaky,+multicluster
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  name: integ-istiodremote
  node_selector:
    testing: test-pool
  requirements:
  - cache
  - kind
  - gocache
  resources: multicluster
  types:
  - presubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.kube.reachability
  env:
  - name: VARIANT
    value: distroless
  - name: TEST_SELECT
    value: -multicluster
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  name: integ-distroless
  node_selector:
    testing: test-pool
  requirements:
  - cache
  - kind
  - gocache
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.kube.reachability
  env:
  - name: DOCKER_IN_DOCKER_IPV6_ENABLED
    value: "true"
  - name: IP_FAMILY
    value: ipv6
  - name: TEST_SELECT
    value: -multicluster
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  name: integ-ipv6
  requirements:
  - cache
  - kind
  - gocache
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.operator.kube.presubmit
  env:
  - name: TEST_SELECT
    value: -postsubmit,-flaky,-multicluster
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  name: integ-operator-controller
  node_selector:
    testing: test-pool
  requirements:
  - cache
  - kind
  - gocache
  types:
  - presubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.pilot.kube
  env:
  - name: TEST_SELECT
    value: -multicluster
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  name: integ-pilot
  node_selector:
    testing: test-pool
  requirements:
  - cache
  - kind
  - gocache
  types:
  - postsubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - --topology
  - MULTICLUSTER
  - test.integration.pilot.kube
  env:
  - name: TEST_SELECT
    value: -multicluster
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  name: integ-pilot-multicluster
  node_selector:
    testing: test-pool
  requirements:
  - cache
  - kind
  - gocache
  resources: multicluster
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - --topology
  - MULTICLUSTER
  - test.integration.pilot.kube
  env:
  - name: TEST_SELECT
    value: -multicluster
  - name: INTEGRATION_TEST_FLAGS
    value: --istio.test.istio.istiodlessRemotes
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  modifiers:
  - presubmit_optional
  - presubmit_skipped
  - hidden
  name: integ-pilot-istiodless-mc
  node_selector:
    testing: test-pool
  requirements:
  - cache
  - kind
  - gocache
  resources: multicluster
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.security.kube
  env:
  - name: TEST_SELECT
    value: -multicluster
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  name: integ-security
  node_selector:
    testing: test-pool
  requirements:
  - cache
  - kind
  - gocache
  types:
  - postsubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration-fuzz.security.fuzz.kube
  cron: 0 7 * * *
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  name: integ-security-fuzz
  node_selector:
    testing: test-pool
  requirements:
  - cache
  - kind
  - gocache
  types:
  - periodic
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - --topology
  - MULTICLUSTER
  - test.integration.security.kube
  env:
  - name: TEST_SELECT
    value: -multicluster
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  name: integ-security-multicluster
  node_selector:
    testing: test-pool
  requirements:
  - cache
  - kind
  - gocache
  resources: multicluster
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - --topology
  - MULTICLUSTER
  - test.integration.security.kube
  env:
  - name: TEST_SELECT
    value: -multicluster
  - name: INTEGRATION_TEST_FLAGS
    value: --istio.test.istio.istiodlessRemotes
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  modifiers:
  - presubmit_optional
  - presubmit_skipped
  - hidden
  name: integ-security-istiodless-mc
  node_selector:
    testing: test-pool
  requirements:
  - cache
  - kind
  - gocache
  resources: multicluster
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.telemetry.kube
  env:
  - name: TEST_SELECT
    value: -multicluster
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  name: integ-telemetry
  node_selector:
    testing: test-pool
  requirements:
  - cache
  - kind
  - gocache
  types:
  - postsubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.helm.kube
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  name: integ-helm
  node_selector:
    testing: test-pool
  requirements:
  - cache
  - kind
  - gocache
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - --node-image
  - kindest/node:v1.16.15
  - test.integration.kube.presubmit
  env:
  - name: INTEGRATION_TEST_FLAGS
    value: ' --istio.test.retries=1 '
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  name: integ-k8s-116
  node_selector:
    testing: test-pool
  requirements:
  - cache
  - kind
  - gocache
  timeout: 4h0m0s
  types:
  - postsubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - --node-image
  - kindest/node:v1.17.17
  - --kind-config
  - prow/config/endpointslice.yaml
  - test.integration.kube.presubmit
  env:
  - name: INTEGRATION_TEST_FLAGS
    value: ' --istio.test.retries=1 '
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  name: integ-k8s-117
  node_selector:
    testing: test-pool
  requirements:
  - cache
  - kind
  - gocache
  timeout: 4h0m0s
  types:
  - postsubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - --node-image
  - kindest/node:v1.18.19
  - test.integration.kube.presubmit
  env:
  - name: INTEGRATION_TEST_FLAGS
    value: ' --istio.test.retries=1 '
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  name: integ-k8s-118
  node_selector:
    testing: test-pool
  requirements:
  - cache
  - kind
  - gocache
  timeout: 4h0m0s
  types:
  - postsubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - --node-image
  - kindest/node:v1.19.11
  - test.integration.kube.presubmit
  env:
  - name: INTEGRATION_TEST_FLAGS
    value: ' --istio.test.retries=1 '
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  name: integ-k8s-119
  node_selector:
    testing: test-pool
  requirements:
  - cache
  - kind
  - gocache
  timeout: 4h0m0s
  types:
  - postsubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - --node-image
  - gcr.io/istio-testing/kind-node:v1.20.7
  - test.integration.kube.presubmit
  env:
  - name: INTEGRATION_TEST_FLAGS
    value: ' --istio.test.retries=1 '
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  name: integ-k8s-120
  node_selector:
    testing: test-pool
  requirements:
  - cache
  - kind
  - gocache
  timeout: 4h0m0s
  types:
  - postsubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - --node-image
  - gcr.io/istio-testing/kind-node:v1.22.0
  - test.integration.kube.presubmit
  env:
  - name: INTEGRATION_TEST_FLAGS
    value: ' --istio.test.retries=1 '
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  name: integ-k8s-122
  node_selector:
    testing: test-pool
  requirements:
  - cache
  - kind
  - gocache
  timeout: 4h0m0s
  types:
  - postsubmit
- command:
  - entrypoint
  - prow/integ-suite-kind.sh
  - test.integration.kube.presubmit
  env:
  - name: INTEGRATION_TEST_FLAGS
    value: ' --istio.test.retries=1 --istio.test.istio.enableCNI=true '
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  name: integ-cni
  node_selector:
    testing: test-pool
  requirements:
  - cache
  - kind
  - gocache
  timeout: 4h0m0s
  types:
  - postsubmit
- command:
  - make
  - test.integration.analyze
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  name: analyze-tests
  node_selector:
    testing: test-pool
  requirements:
  - cache
  - gocache
  types:
  - presubmit
- command:
  - make
  - lint
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  name: lint
  node_selector:
    testing: test-pool
  requirements:
  - cache
  - gocache
  resources: lint
  types:
  - presubmit
- command:
  - make
  - gen-check
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  name: gencheck
  node_selector:
    testing: test-pool
  requirements:
  - cache
  - gocache
  types:
  - presubmit
- command:
  - ../test-infra/tools/check_release_notes.sh
  - --token-path=/etc/github-token/oauth
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  name: release-notes
  node_selector:
    testing: test-pool
  repos:
  - istio/test-infra@master
  - istio/tools@master
  requirements:
  - cache
  - github
  - gocache
  types:
  - presubmit
org: istio
repo: istio
requirement_presets:
  cache:
    annotations: null
    env: null
    labels: null
    volumeMounts:
    - mountPath: /home/prow/go/pkg
      name: build-cache
      subPath: gomod
    volumes:
    - hostPath:
        path: /var/tmp/prow/cache
        type: DirectoryOrCreate
      name: build-cache
  docker:
    annotations: null
    env: null
    labels: null
    volumeMounts:
    - mountPath: /var/lib/docker
      name: docker-root
    volumes:
    - emptyDir: {}
      name: docker-root
  github:
    annotations: null
    env: null
    labels: null
    volumeMounts:
    - mountPath: /etc/github-token
      name: github
      readOnly: true
    volumes:
    - name: github
      secret:
        secretName: oauth-token
  github-optional:
    annotations: null
    env: null
    labels: null
    volumeMounts:
    - mountPath: /etc/github-token
      name: github
      readOnly: true
    volumes:
    - name: github
      secret:
        optional: true
        secretName: oauth-token
  gocache:
    annotations: null
    env: null
    labels: null
    volumeMounts:
    - mountPath: /gocache
      name: build-cache
      subPath: gocache
    volumes:
    - hostPath:
        path: /var/tmp/prow/cache
        type: DirectoryOrCreate
      name: build-cache
  kind:
    annotations: null
    env: null
    labels: null
    volumeMounts:
    - mountPath: /lib/modules
      name: modules
      readOnly: true
    - mountPath: /sys/fs/cgroup
      name: cgroup
      readOnly: true
    - mountPath: /var/lib/docker
      name: docker-root
    volumes:
    - hostPath:
        path: /lib/modules
        type: Directory
      name: modules
    - hostPath:
        path: /sys/fs/cgroup
        type: Directory
      name: cgroup
    - emptyDir: {}
      name: docker-root
  release:
    annotations: null
    env: null
    labels:
      preset-release-pipeline: "true"
    volumeMounts: null
    volumes: null
requirements:
- gocache
resources_presets:
  benchmark:
    limits:
      memory: 24Gi
    requests:
      cpu: "15"
      memory: 8Gi
  default:
    limits:
      memory: 24Gi
    requests:
      cpu: "5"
      memory: 3Gi
  lint:
    limits:
      memory: 24Gi
    requests:
      cpu: "3"
      memory: 16Gi
  multicluster:
    limits:
      memory: 24Gi
    requests:
      cpu: "8"
      memory: 3Gi
