branches:
- release-1.9
image: gcr.io/istio-testing/build-tools:release-1.9-2021-01-13T15-02-13
jobs:
- command:
  - make
  - build
  name: build
- command:
  - make
  - lint
  name: lint
- command:
  - make
  - test
  name: test
- command:
  - make
  - gen-check
  name: gencheck
org: istio
repo: pkg
resources:
  default:
    limits:
      cpu: "3"
      memory: 24Gi
    requests:
      cpu: "1"
      memory: 3Gi
