branches:
- release-1.11
image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
jobs:
- command:
  - make
  - build
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  name: build
  node_selector:
    testing: test-pool
  requirements:
  - cache
- command:
  - make
  - lint
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  name: lint
  node_selector:
    testing: test-pool
  requirements:
  - cache
- command:
  - make
  - test
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  name: test
  node_selector:
    testing: test-pool
  requirements:
  - cache
- command:
  - make
  - gen-check
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  name: gencheck
  node_selector:
    testing: test-pool
  requirements:
  - cache
- command:
  - ../test-infra/tools/automator/automator.sh
  - --org=istio
  - --repo=istio
  - '--title=Automator: update istio/pkg@$AUTOMATOR_SRC_BRANCH dependency in $AUTOMATOR_ORG/$AUTOMATOR_REPO@$AUTOMATOR_BRANCH'
  - --labels=auto-merge,release-notes-none
  - --modifier=update_pkg_dep
  - --token-path=/etc/github-token/oauth
  - --git-exclude=^common/
  - --cmd=go get istio.io/pkg@$AUTOMATOR_SHA && go mod tidy && make clean gen
  image: gcr.io/istio-testing/build-tools:release-1.11-2022-02-15T14-29-34
  name: update_pkg_dep
  node_selector:
    testing: test-pool
  repos:
  - istio/test-infra@master
  requirements:
  - cache
  - github
  types:
  - postsubmit
org: istio
repo: pkg
requirement_presets:
  cache:
    annotations: null
    env: null
    labels: null
    volumeMounts:
    - mountPath: /home/prow/go/pkg
      name: build-cache
      subPath: gomod
    volumes:
    - hostPath:
        path: /var/tmp/prow/cache
        type: DirectoryOrCreate
      name: build-cache
  docker:
    annotations: null
    env: null
    labels: null
    volumeMounts:
    - mountPath: /var/lib/docker
      name: docker-root
    volumes:
    - emptyDir: {}
      name: docker-root
  github:
    annotations: null
    env: null
    labels: null
    volumeMounts:
    - mountPath: /etc/github-token
      name: github
      readOnly: true
    volumes:
    - name: github
      secret:
        secretName: oauth-token
  github-optional:
    annotations: null
    env: null
    labels: null
    volumeMounts:
    - mountPath: /etc/github-token
      name: github
      readOnly: true
    volumes:
    - name: github
      secret:
        optional: true
        secretName: oauth-token
  gocache:
    annotations: null
    env: null
    labels: null
    volumeMounts:
    - mountPath: /gocache
      name: build-cache
      subPath: gocache
    volumes:
    - hostPath:
        path: /var/tmp/prow/cache
        type: DirectoryOrCreate
      name: build-cache
  kind:
    annotations: null
    env: null
    labels: null
    volumeMounts:
    - mountPath: /lib/modules
      name: modules
      readOnly: true
    - mountPath: /sys/fs/cgroup
      name: cgroup
      readOnly: true
    - mountPath: /var/lib/docker
      name: docker-root
    volumes:
    - hostPath:
        path: /lib/modules
        type: Directory
      name: modules
    - hostPath:
        path: /sys/fs/cgroup
        type: Directory
      name: cgroup
    - emptyDir: {}
      name: docker-root
  release:
    annotations: null
    env: null
    labels:
      preset-release-pipeline: "true"
    volumeMounts: null
    volumes: null
resources_presets:
  benchmark:
    limits:
      memory: 24Gi
    requests:
      cpu: "15"
      memory: 8Gi
  default:
    limits:
      cpu: "3"
      memory: 24Gi
    requests:
      cpu: "1"
      memory: 3Gi
  lint:
    limits:
      memory: 24Gi
    requests:
      cpu: "3"
      memory: 16Gi
  multicluster:
    limits:
      memory: 24Gi
    requests:
      cpu: "8"
      memory: 3Gi
