org: istio
repo: pkg
support_release_branching: true
image: gcr.io/istio-testing/build-tools:master-d1c937bacd5fd54df479b065f2e56f3d643f68cb

jobs:
  - name: build
    command: [make, build]

  - name: lint
    command: [make, lint]

  - name: test
    command: [make, test]

  - name: gencheck
    command: [make, gen-check]

  - name: update_pkg_dep
    types: [postsubmit]
    command:
    - ../test-infra/tools/automator/automator.sh
    - --org=$AUTOMATOR_ORG
    - --repo=istio
    - "--title=Automator: update istio/pkg@$AUTOMATOR_SRC_BRANCH dependency in $AUTOMATOR_ORG/$AUTOMATOR_REPO@$AUTOMATOR_BRANCH"
    - --labels=auto-merge,release-notes-none
    - --modifier=update_pkg_dep
    - --token-path=/etc/github-token/oauth
    - --git-exclude=^common/
    - --cmd=go get istio.io/pkg@$AUTOMATOR_SHA && go mod tidy && make clean gen
    requirements: [github]
    repos: [istio/test-infra@master]
    env:
    - name: AUTOMATOR_ORG
      value: istio
