branches:
- release-1.6
image: gcr.io/istio-testing/build-tools-proxy:release-1.6-2020-05-08T22-06-04
jobs:
- command:
  - ./prow/proxy-presubmit.sh
  name: test
  type: presubmit
- command:
  - ./prow/proxy-presubmit-asan.sh
  name: test-asan
  type: presubmit
- command:
  - ./prow/proxy-presubmit-tsan.sh
  name: test-tsan
  type: presubmit
- command:
  - ./prow/proxy-presubmit-release.sh
  name: release-test
  requirements:
  - gcp
  type: presubmit
- command:
  - entrypoint
  - ./prow/proxy-presubmit-wasm.sh
  name: check-wasm
  requirements:
  - docker
  type: presubmit
- command:
  - entrypoint
  - ./prow/proxy-postsubmit.sh
  name: release
  requirements:
  - gcp
  - docker
  timeout: 4h0m0s
  type: postsubmit
node_selector:
  testing: build-pool
org: istio
repo: proxy
resources:
  default:
    limits:
      cpu: "64"
      memory: 240G
    requests:
      cpu: "30"
      memory: 100G
