branches:
- release-1.7
image: gcr.io/istio-testing/build-tools-proxy:release-1.7-2020-11-25T22-57-38
jobs:
- command:
  - ./prow/proxy-presubmit.sh
  name: test
  types: [presubmit]
- command:
  - ./prow/proxy-presubmit-asan.sh
  name: test-asan
  types: [presubmit]
- command:
  - ./prow/proxy-presubmit-tsan.sh
  name: test-tsan
  types: [presubmit]
- command:
  - ./prow/proxy-presubmit-release.sh
  name: release-test
  requirements:
  - gcp
  types: [presubmit]
- command:
  - entrypoint
  - ./prow/proxy-presubmit-wasm.sh
  name: check-wasm
  requirements:
  - docker
  types: [presubmit]
- command:
  - entrypoint
  - ./prow/proxy-postsubmit.sh
  name: release
  requirements:
  - gcp
  - docker
  timeout: 4h0m0s
  types: [postsubmit]
- command:
  - ../test-infra/tools/automator/automator.sh
  - --org=istio
  - --repo=istio
  - '--title=Automator: update proxy@$AUTOMATOR_SRC_BRANCH in $AUTOMATOR_ORG/$AUTOMATOR_REPO@$AUTOMATOR_BRANCH'
  - --labels=auto-merge,release-notes-none
  - --modifier=update_proxy_dep
  - --token-path=/etc/github-token/oauth
  - --cmd=bin/update_proxy.sh $AUTOMATOR_SHA
  image: gcr.io/istio-testing/build-tools:release-1.7-2020-11-25T22-57-38
  name: update-istio
  repos:
  - istio/test-infra@master
  requirements:
  - github
  timeout: 4h0m0s
  types: [postsubmit]
node_selector:
  testing: build-pool
org: istio
repo: proxy
resources:
  default:
    limits:
      cpu: "64"
      memory: 240G
    requests:
      cpu: "30"
      memory: 100G
