branches:
- release-1.7
image: gcr.io/istio-testing/build-tools-proxy:release-release-1.7-2020-07-16T22-57-32
jobs:
- command:
  - ./prow/proxy-presubmit.sh
  name: test
  type: presubmit
- command:
  - ./prow/proxy-presubmit-asan.sh
  name: test-asan
  type: presubmit
- command:
  - ./prow/proxy-presubmit-tsan.sh
  name: test-tsan
  type: presubmit
- command:
  - ./prow/proxy-presubmit-release.sh
  name: release-test
  requirements:
  - gcp
  type: presubmit
- command:
  - ./prow/proxy-presubmit-centos-release.sh
  image: gcr.io/istio-testing/build-tools-centos:master-2020-07-22T15-36-22
  modifiers:
  - hidden
  - optional
  name: release-centos-test
  regex: centos
  requirements:
  - gcp
  type: presubmit
- command:
  - entrypoint
  - ./prow/proxy-presubmit-wasm.sh
  name: check-wasm
  requirements:
  - docker
  type: presubmit
- command:
  - entrypoint
  - ./prow/proxy-postsubmit.sh
  name: release
  requirements:
  - gcp
  - docker
  timeout: 4h0m0s
  type: postsubmit
- command:
  - ../test-infra/tools/automator/automator.sh
  - --org=istio
  - --repo=istio
  - '--title=Automator: update proxy@$AUTOMATOR_SRC_BRANCH in $AUTOMATOR_ORG/$AUTOMATOR_REPO@$AUTOMATOR_BRANCH'
  - --labels=auto-merge,release-notes-none
  - --modifier=update_proxy_dep
  - --token-path=/etc/github-token/oauth
  - --cmd=bin/update_proxy.sh $AUTOMATOR_SHA
  image: gcr.io/istio-testing/build-tools:master-2020-07-22T15-36-22
  name: update-istio
  repos:
  - istio/test-infra@master
  requirements:
  - github
  timeout: 4h0m0s
  type: postsubmit
node_selector:
  testing: build-pool
org: istio
repo: proxy
resources:
  default:
    limits:
      cpu: "64"
      memory: 240G
    requests:
      cpu: "30"
      memory: 100G
