branches:
- release-1.11
image: gcr.io/istio-testing/build-tools:release-1.11-2021-11-15T12-29-57
jobs:
- command:
  - make
  - lint
  image: gcr.io/istio-testing/build-tools:release-1.11-2021-11-15T12-29-57
  name: lint
  node_selector:
    testing: test-pool
  requirements:
  - cache
- command:
  - make
  - test
  image: gcr.io/istio-testing/build-tools:release-1.11-2021-11-15T12-29-57
  name: test
  node_selector:
    testing: test-pool
  requirements:
  - cache
- command:
  - make
  - gen-check
  image: gcr.io/istio-testing/build-tools:release-1.11-2021-11-15T12-29-57
  name: gencheck
  node_selector:
    testing: test-pool
  requirements:
  - cache
- command:
  - entrypoint
  - test/publish.sh
  image: gcr.io/istio-testing/build-tools:release-1.11-2021-11-15T12-29-57
  name: dry-run
  service_account_name: prowjob-advanced-sa
  node_selector:
    testing: test-pool
  regex: \.go$|\.sh$
  requirements:
  - cache
  - docker
  resources: build
- command:
  - release/build-warning.sh
  image: gcr.io/istio-testing/build-tools:release-1.11-2021-11-15T12-29-57
  modifiers:
  - presubmit_optional
  name: build-warning
  node_selector:
    testing: test-pool
  regex: ^release/trigger-build$
  requirements:
  - cache
  types:
  - presubmit
- command:
  - release/publish-warning.sh
  image: gcr.io/istio-testing/build-tools:release-1.11-2021-11-15T12-29-57
  modifiers:
  - presubmit_optional
  name: publish-warning
  node_selector:
    testing: test-pool
  regex: ^release/trigger-publish$
  requirements:
  - cache
  types:
  - presubmit
- command:
  - entrypoint
  - release/build.sh
  image: gcr.io/istio-testing/build-tools:release-1.11-2021-11-15T12-29-57
  name: build-release
  node_selector:
    testing: test-pool
  regex: ^release/trigger-build$
  requirements:
  - cache
  - release
  - docker
  - github-optional
  resources: build
  types:
  - postsubmit
- command:
  - entrypoint
  - release/publish.sh
  image: gcr.io/istio-testing/build-tools:release-1.11-2021-11-15T12-29-57
  name: publish-release
  node_selector:
    testing: test-pool
  regex: ^release/trigger-publish$
  requirements:
  - cache
  - release
  - docker
  resources: build
  types:
  - postsubmit
org: istio
repo: release-builder
resources_presets:
  benchmark:
    limits:
      memory: 24Gi
    requests:
      cpu: "15"
      memory: 8Gi
  build:
    limits:
      cpu: "8"
      memory: 24Gi
    requests:
      cpu: "5"
      memory: 3Gi
  default:
    limits:
      cpu: "3"
      memory: 24Gi
    requests:
      cpu: "1"
      memory: 3Gi
  lint:
    limits:
      memory: 24Gi
    requests:
      cpu: "3"
      memory: 16Gi
  multicluster:
    limits:
      memory: 24Gi
    requests:
      cpu: "8"
      memory: 3Gi
