branches:
- release-1.10
image: gcr.io/istio-testing/build-tools:release-1.10-2021-07-21T19-44-12
jobs:
- command:
  - make
  - lint
  name: lint
  node_selector:
    testing: test-pool
  requirements:
  - cache
- command:
  - make
  - test
  name: test
  node_selector:
    testing: test-pool
  requirements:
  - cache
- command:
  - make
  - gen-check
  name: gencheck
  node_selector:
    testing: test-pool
  requirements:
  - cache
- command:
  - entrypoint
  - test/publish.sh
  name: dry-run
  node_selector:
    testing: test-pool
  regex: \.go$|\.sh$
  requirements:
  - cache
  - gcp
  - docker
  resources: build
- command:
  - release/build-warning.sh
  modifiers:
  - presubmit_optional
  name: build-warning
  node_selector:
    testing: test-pool
  regex: ^release/trigger-build$
  requirements:
  - cache
  types:
  - presubmit
- command:
  - release/publish-warning.sh
  modifiers:
  - presubmit_optional
  name: publish-warning
  node_selector:
    testing: test-pool
  regex: ^release/trigger-publish$
  requirements:
  - cache
  types:
  - presubmit
- command:
  - entrypoint
  - release/build.sh
  name: build-release
  node_selector:
    testing: test-pool
  regex: ^release/trigger-build$
  requirements:
  - cache
  - release
  - docker
  - github-optional
  resources: build
  types:
  - postsubmit
- command:
  - entrypoint
  - release/publish.sh
  name: publish-release
  node_selector:
    testing: test-pool
  regex: ^release/trigger-publish$
  requirements:
  - cache
  - release
  - docker
  resources: build
  types:
  - postsubmit
org: istio
repo: release-builder
requirement_presets:
  cache:
    env: null
    labels: null
    volumeMounts:
    - mountPath: /home/prow/go/pkg
      name: build-cache
      subPath: gomod
    volumes:
    - hostPath:
        path: /var/tmp/prow/cache
        type: DirectoryOrCreate
      name: build-cache
  deploy:
    env: null
    labels:
      preset-prow-deployer-service-account: "true"
    volumeMounts: null
    volumes: null
  docker:
    env: null
    labels: null
    volumeMounts:
    - mountPath: /var/lib/docker
      name: docker-root
    volumes:
    - emptyDir: {}
      name: docker-root
  gcp:
    env: null
    labels:
      preset-service-account: "true"
    volumeMounts: null
    volumes: null
  github:
    env: null
    labels: null
    volumeMounts:
    - mountPath: /etc/github-token
      name: github
      readOnly: true
    volumes:
    - name: github
      secret:
        secretName: oauth-token
  gocache:
    env: null
    labels: null
    volumeMounts:
    - mountPath: /gocache
      name: build-cache
      subPath: gocache
    volumes:
    - hostPath:
        path: /var/tmp/prow/cache
        type: DirectoryOrCreate
      name: build-cache
  kind:
    env: null
    labels: null
    volumeMounts:
    - mountPath: /lib/modules
      name: modules
      readOnly: true
    - mountPath: /sys/fs/cgroup
      name: cgroup
      readOnly: true
    - mountPath: /var/lib/docker
      name: docker-root
    volumes:
    - hostPath:
        path: /lib/modules
        type: Directory
      name: modules
    - hostPath:
        path: /sys/fs/cgroup
        type: Directory
      name: cgroup
    - emptyDir: {}
      name: docker-root
  release:
    env: null
    labels:
      preset-release-pipeline: "true"
    volumeMounts: null
    volumes: null
resources:
  benchmark:
    limits:
      memory: 24Gi
    requests:
      cpu: "15"
      memory: 8Gi
  build:
    limits:
      cpu: "8"
      memory: 24Gi
    requests:
      cpu: "5"
      memory: 3Gi
  default:
    limits:
      cpu: "3"
      memory: 24Gi
    requests:
      cpu: "1"
      memory: 3Gi
  lint:
    limits:
      memory: 24Gi
    requests:
      cpu: "3"
      memory: 16Gi
