branches:
- release-1.4
image: gcr.io/istio-testing/build-tools:2019-10-25T16-21-08
jobs:
- command:
  - make
  - build
  name: build
- command:
  - make
  - lint
  name: lint
- command:
  - make
  - test
  name: test
org: istio
repo: tools
resources:
  default:
    limits:
      cpu: "3"
      memory: 24Gi
    requests:
      cpu: 500m
      memory: 3Gi
