branches:
- release-1.11
image: gcr.io/istio-testing/build-tools:master-2021-07-13T17-42-03
jobs:
- command:
  - make
  - build
  image: gcr.io/istio-testing/build-tools:master-2021-07-13T17-42-03
  name: build
  node_selector:
    testing: test-pool
  requirements:
  - cache
- command:
  - make
  - lint
  image: gcr.io/istio-testing/build-tools:master-2021-07-13T17-42-03
  name: lint
  node_selector:
    testing: test-pool
  requirements:
  - cache
- command:
  - make
  - test
  image: gcr.io/istio-testing/build-tools:master-2021-07-13T17-42-03
  name: test
  node_selector:
    testing: test-pool
  requirements:
  - cache
- command:
  - make
  - gen-check
  image: gcr.io/istio-testing/build-tools:master-2021-07-13T17-42-03
  name: gencheck
  node_selector:
    testing: test-pool
  requirements:
  - cache
- command:
  - entrypoint
  - make
  - containers
  image: gcr.io/istio-testing/build-tools:master-2021-07-13T17-42-03
  name: containers
  node_selector:
    testing: test-pool
  regex: docker/.+|cmd/.+
  requirements:
  - cache
  - gcp
  - docker
  resources: build
  types:
  - postsubmit
- command:
  - entrypoint
  - make
  - containers-test
  image: gcr.io/istio-testing/build-tools:master-2021-07-13T17-42-03
  name: containers-test
  node_selector:
    testing: test-pool
  regex: docker/.+|cmd/.+
  requirements:
  - cache
  - gcp
  - docker
  resources: build
  types:
  - presubmit
- command:
  - entrypoint
  - make
  - -C
  - perf_dashboard
  - deploy
  image: gcr.io/istio-testing/build-tools:master-2021-07-13T17-42-03
  name: deploy-perf-dashboard
  node_selector:
    testing: test-pool
  regex: ^perf_dashboard/
  requirements:
  - cache
  - docker
  - gcp
  types:
  - postsubmit
org: istio
repo: tools
requirement_presets:
  cache:
    annotations: null
    env: null
    labels: null
    volumeMounts:
    - mountPath: /home/prow/go/pkg
      name: build-cache
      subPath: gomod
    volumes:
    - hostPath:
        path: /tmp/prow/cache
        type: DirectoryOrCreate
      name: build-cache
  deploy:
    annotations: null
    env: null
    labels:
      preset-prow-deployer-service-account: "true"
    volumeMounts: null
    volumes: null
  docker:
    annotations: null
    env: null
    labels: null
    volumeMounts:
    - mountPath: /var/lib/docker
      name: docker-root
    volumes:
    - emptyDir: {}
      name: docker-root
  gcp:
    annotations: null
    env: null
    labels:
      preset-service-account: "true"
    volumeMounts: null
    volumes: null
  github:
    annotations: null
    env: null
    labels: null
    volumeMounts:
    - mountPath: /etc/github-token
      name: github
      readOnly: true
    volumes:
    - name: github
      secret:
        secretName: oauth-token
  github-optional:
    annotations: null
    env: null
    labels: null
    volumeMounts:
    - mountPath: /etc/github-token
      name: github
      readOnly: true
    volumes:
    - name: github
      secret:
        optional: true
        secretName: oauth-token
  gocache:
    annotations: null
    env: null
    labels: null
    volumeMounts:
    - mountPath: /gocache
      name: build-cache
      subPath: gocache
    volumes:
    - hostPath:
        path: /tmp/prow/cache
        type: DirectoryOrCreate
      name: build-cache
  kind:
    annotations: null
    env: null
    labels: null
    volumeMounts:
    - mountPath: /lib/modules
      name: modules
      readOnly: true
    - mountPath: /sys/fs/cgroup
      name: cgroup
      readOnly: true
    - mountPath: /var/lib/docker
      name: docker-root
    volumes:
    - hostPath:
        path: /lib/modules
        type: Directory
      name: modules
    - hostPath:
        path: /sys/fs/cgroup
        type: Directory
      name: cgroup
    - emptyDir: {}
      name: docker-root
  release:
    annotations: null
    env: null
    labels:
      preset-release-pipeline: "true"
    volumeMounts: null
    volumes: null
resources:
  benchmark:
    limits:
      memory: 24Gi
    requests:
      cpu: "15"
      memory: 8Gi
  build:
    limits:
      cpu: "8"
      memory: 24Gi
    requests:
      cpu: "8"
      memory: 4Gi
  default:
    limits:
      cpu: "3"
      memory: 24Gi
    requests:
      cpu: "1"
      memory: 3Gi
  lint:
    limits:
      memory: 24Gi
    requests:
      cpu: "3"
      memory: 16Gi
  multicluster:
    limits:
      memory: 24Gi
    requests:
      cpu: "8"
      memory: 3Gi
