apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: @@-submit-queue
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: submit-queue
        target-repo: @@
    spec:
      containers:
      - name: submit-queue
        command:
        - /mungegithub
        - --dry-run=false
        - --stderrthreshold=INFO
        - --config-path=/etc/munge-config/config
        image: gcr.io/istio-testing/mungegithub/submit-queue:Oct-12-0cf14519c96699c79b900e03e582e6f6009c60fb
        ports:
        - name: status
          containerPort: 8080
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
        volumeMounts:
        - mountPath: /etc/munge-config
          name: munge-config
        - mountPath: /etc/secret-volume
          name: secret-volume
        - mountPath: /etc/hook-secret-volume
          name: hook-secret-volume
        - mountPath: /gitrepos
          name: repo
        - mountPath: /cache
          name: cache-volume
      volumes:
      - name: munge-config
        configMap:
          name: @@-sq-config
      - name: secret-volume
        secret:
          secretName: @@-github-token
      - name: hook-secret-volume
        secret:
          secretName: @@-github-secret
      - name: repo
        emptyDir: {}
      - name: cache-volume
        persistentVolumeClaim:
          claimName: mungegithub-@@-cache
