apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: boskos-metrics
  labels:
    app: boskos-metrics
  namespace: boskos
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: boskos-metrics
      namespace: test-pods
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: metrics
        image: gcr.io/k8s-testimages/metrics:v20180604-ea866c2e8
        args:
        - --resource-type=gke-perf-preset,gcp-perf-test,gcp-project,gke-e2e-test,gke-e2e-test-latest
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /prometheus
            port: 8080
          periodSeconds: 1
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 10
      nodeSelector:
        prod: prow
