apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: boskos-reaper
  labels:
    app: boskos-reaper
  namespace: boskos
spec:
  replicas: 1  # one canonical source of resources
  template:
    metadata:
      labels:
        app: boskos-reaper
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: boskos-reaper
        image: gcr.io/istio-testing/reaper:v20180214-ea0601591
        args:
        - --resource-type=gcp-project,gke-e2e-test
