kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: metrics-fetcher
  namespace: metrics
spec:
  replicas: 1
  strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
  template:
    metadata:
      labels:
        istio: metrics-fetcher
    spec:
      containers:
      - name: metrics-fetcher
        image: gcr.io/istio-testing/metrics_fetcher:1530218034842
        args:
        - --service_account_json=/etc/service-account/service-account.json
        - --alsologtostderr
        ports:
        - containerPort: 9103
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/service-account
          name: service-account
          readOnly: true
        readinessProbe:
          httpGet:
            path: /metrics
            port: 9103
          periodSeconds: 1
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 10
      volumes:
      - name: service-account
        secret:
          secretName: metrics-service-account

